Production/Production/src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

Production/Production/src/objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Day_in_Month__c</fullName>
        <label>Billing Days in Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CURRENT_OVERDUE__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Current Overdue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Limit__c</fullName>
        <label>Call Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Treatment_Path__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Treatment Path</label>
        <referenceTo>Collection_Path__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DAYS_61_90__c</fullName>
        <label>DAYS 61-90</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exposure_Value__c</fullName>
        <label>Exposure Value</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Promise_to_Pay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Promise to Pay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UNBILLED_AMOUNT__c</fullName>
        <label>Unbilled Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/Production/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

Production/Production/src/objects/Collection_Path__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag indicates if the Path is active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Collection Path</label>
    <nameField>
        <label>Collection Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Production/Production/src/objects/Collections_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Various settings for Collections</description>
    <fields>
        <fullName>Approval_Term_Threshold__c</fullName>
        <description>The number of periods above which a PP will require approval before it is Active/Open.</description>
        <label>Approval Term Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>P2P_Path_for_30_60d_Debt__c</fullName>
        <label>P2P Path for 30 60d Debt</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P2P_Path_for_Less_than_30d_Debt__c</fullName>
        <label>P2P Path for Less than 30d Debt</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PA_Confirmation_Email_Template_AOL__c</fullName>
        <description>The id of the PP Confirmation Template that is sent as an email to the AOL customer once a PP has been activated and a case created.</description>
        <label>PA Confirmation Email Template AOL</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PA_Confirmation_Email_Template_TT__c</fullName>
        <description>The id of the PP Confirmation Template that is sent as an email to the Talk Talk customer once a PP has been activated and a case created.</description>
        <label>PA Confirmation Email Template TT</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PP_Call_Limit__c</fullName>
        <label>PP Call Limit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PTP_Confirmation_Email_Template_AOL__c</fullName>
        <description>The id of the P2P Confirmation Template that is sent as an email to the AOL customer once a P2P has been activated and a case created.</description>
        <label>PTP Confirmation Email Template AOL</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PTP_Confirmation_Email_Template_TT__c</fullName>
        <description>The id of the P2P Confirmation Template that is sent as an email to the TT customer once a P2P has been activated and a case created.</description>
        <label>PTP Confirmation Email Template TT</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Plan_Path__c</fullName>
        <label>Payment Plan Path</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Collections Settings</label>
</CustomObject>

Production/Production/src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_ID__c</fullName>
        <externalId>true</externalId>
        <label>Payment ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Payment_Source_Code__c</fullName>
        <label>Payment Source Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Production/Production/src/objects/Payment_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Call_Limit__c</fullName>
        <formula>Billing_Account__r.Call_Limit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Call Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Collection_Path__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collection Path</label>
        <referenceTo>Collection_Path__c</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DAYS_61_90__c</fullName>
        <formula>Billing_Account__r.DAYS_61_90__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DAYS 61-90</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_of_First_Installment__c</fullName>
        <label>Date of First Installment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>One_off_Payment__c</fullName>
        <defaultValue>0</defaultValue>
        <label>One off Payment</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unbilled_Amount__c</fullName>
        <formula>Billing_Account__r.UNBILLED_AMOUNT__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unbilled Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Production/Production/src/objects/Promise_to_Pay__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Due</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Promise to Pay</relationshipLabel>
        <relationshipName>Promise_to_Pay</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collection_Path__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collection Path</label>
        <referenceTo>Collection_Path__c</referenceTo>
        <relationshipLabel>Promise to Pay</relationshipLabel>
        <relationshipName>Promise_to_Pay</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DAYS_61_90__c</fullName>
        <formula>Billing_Account__r.DAYS_61_90__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DAYS 61-90</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>One_off_Payment__c</fullName>
        <defaultValue>0</defaultValue>
        <label>One off Payment</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Proposed_Payment_Date__c</fullName>
        <label>Proposed Payment Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Promise to Pay</label>
    <nameField>
        <displayFormat>P2P-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promise to Pay</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Production/Production/src/classes/TestPromiseToPayTriggers.cls
@isTest
private class TestPromiseToPayTriggers {
	
	static testmethod void testBeforeUpdate_WithOpenOrClosedStatus_CannotBeModified() {
		
		//Create Custom Setting
		//Collections_Settings__c cs = createCollectionSettings();
		TestHelper.createCollectionSettings(6);
		
		Billing_Account__c ba = new Billing_Account__c(Name = 'Test', CURRENT_OVERDUE__c = 300, Billing_Day_in_Month__c = Date.today().day(), Unbilled_Amount__c = 20, Call_Limit__c = 25, Exposure_Value__c = 120);
		insert ba;
		
		Account acc = new Account (Name = 'Test_Acc_1');
        insert acc;
        
        insert new Asset(Name='TestassetName', AccountId=acc.Id, 	Billing_Account__c=ba.id , Status__c = 'ACTIVE');
		
		Promise_to_Pay__c p2p = new Promise_to_Pay__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Open, 
						Proposed_Payment_Date__c = Date.today().addDays(2), Amount_Due__c = 1000, 	One_off_Payment__c = 100);
		insert p2p;
		
		// ------ EP testing 08/10/2013
		Billing_Account__c testBA = [select Id, Current_Treatment_path__c from Billing_Account__c where Id = :ba.Id];
		system.assert(testBA.Current_Treatment_path__c != null);
		///////////////
		
		
		
		Payment__c payment = new Payment__c();
		payment.Billing_Account__c = ba.id;
		payment.Payment_Source_Code__c = 6;
		payment.Payment_ID__c = '124124124';
		payment.Amount__c = 500;
		
		Payment__c payment1 = new Payment__c();
		payment1.Billing_Account__c = ba.id;
		payment1.Payment_Source_Code__c = 6;
		payment1.Payment_ID__c = '1241241242';
		payment1.Amount__c = 500;
		
		List<Payment__c> payments = new List<Payment__c>{payment, payment1};
		
		insert payments;
		
		
		p2p.Proposed_Payment_Date__c = Date.today().addDays(1);
		
		Test.startTest();
		try {
			update p2p;
		}
		catch (Exception ex) {
			 System.assert(ex.getMessage().indexOf('You don\'t have the permission to edit Open or Closed Promises to Pay.') > 0);
		}
		Test.stopTest();
	}
	
	/* 
	 * Mimicks approval process of Promise To Pay
	 */
	static testmethod void testAfterUpdate_ToOpenStatus_CollectionsCaseCreatedAndEmailSent() {
		
		//Create Custom Setting
		//Collections_Settings__c cs = createCollectionSettings();
		TestHelper.createCollectionSettings(6);
		
		
		Billing_Account__c ba = new Billing_Account__c(Name = 'Test', Billing_Day_in_Month__c = Date.today().day(), CURRENT_OVERDUE__c = 300, Unbilled_Amount__c = 20, Call_Limit__c = 25, 
			Exposure_Value__c = 120, DAYS_61_90__c = 100);
		insert ba;
		
		Account acc = new Account (Name = 'Test_Acc_1');
        insert acc;
        
        insert new Asset(Name='TestassetName', AccountId=acc.Id, 	Billing_Account__c=ba.id , Status__c = 'ACTIVE');
		
		Promise_to_Pay__c p2p = new Promise_to_Pay__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Open, 
			Proposed_Payment_Date__c = Date.today().addDays(2), Amount_Due__c = 1000, One_off_Payment__c = 100);
		insert p2p; //should be saved as 'Saved'
		
		p2p.Status__c = Constants.PaymentPlanStatus_Open;
		
		Test.startTest();
		update p2p;
		Test.stopTest();
		
		//Assert
		
		List<Case> cases = [select Id, Record_Type_Name__c from Case where Billing_Account__c = :ba.Id];
		system.assertEquals(1, cases.size());
		system.assertEquals(Constants.CaseRecordType_Collection, cases[0].Record_Type_Name__c);
	}

	static testmethod void testBeforeInsert_WithNoAgedDebt_StatusSetToOpenAndCaseCreated() {
		
		//Create Custom Setting
		//Collections_Settings__c cs = createCollectionSettings();
		
		TestHelper.createCollectionSettings(6);
		
		Billing_Account__c ba = new Billing_Account__c(Name = 'Test', Billing_Day_in_Month__c = Date.today().day(), CURRENT_OVERDUE__c = 300, Unbilled_Amount__c = 20, Call_Limit__c = 25, Exposure_Value__c = 120);
		insert ba;
		
		Account acc = new Account (Name = 'Test_Acc_1');
        insert acc;
        
        insert new Asset(Name='TestassetName', AccountId=acc.Id, 	Billing_Account__c=ba.id , Status__c = 'ACTIVE');
		
		Promise_to_Pay__c p2p = new Promise_to_Pay__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Open, 
			 Proposed_Payment_Date__c = Date.today().addDays(2), Amount_Due__c = 1000, One_off_Payment__c = 100);
		insert p2p;
		
		//Retrieve and assert
		Promise_to_Pay__c savedP2P = [select Id, Status__c from Promise_to_Pay__c where Billing_Account__c = :ba.Id LIMIT 1];
		List<Case> cases = [select Id, Record_Type_Name__c from Case where Billing_Account__c = :ba.Id];
		
		system.assertEquals(Constants.PaymentPlanStatus_Open, savedP2P.Status__c);
		system.assertEquals(1, cases.size());
		system.assertEquals(Constants.CaseRecordType_Collection, cases[0].Record_Type_Name__c);
	}
	
	static testmethod void testBeforeInsert_WithAgedDebt6190_StatusSetToSavedAndNoCaseCreated() {
		
		//Create Custom Setting
		//Collections_Settings__c cs = createCollectionSettings();
		
		TestHelper.createCollectionSettings(6);
		
		Billing_Account__c ba = new Billing_Account__c(Name = 'Test', CURRENT_OVERDUE__c = 300, Unbilled_Amount__c = 20, Call_Limit__c = 25, 
						Billing_Day_in_Month__c = Date.today().day(), Exposure_Value__c = 120, DAYS_61_90__c = 100);
		insert ba;
		
		Account acc = new Account (Name = 'Test_Acc_1');
        insert acc;
        
        insert new Asset(Name='TestassetName', AccountId=acc.Id, 	Billing_Account__c=ba.id , Status__c = 'ACTIVE');
		
		Promise_to_Pay__c p2p = new Promise_to_Pay__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Open, 
			 Proposed_Payment_Date__c = Date.today().addDays(2), Amount_Due__c = 1000, One_off_Payment__c = 100);
		insert p2p;
		
		//Retrieve and assert
		Promise_to_Pay__c savedP2P = [select Id, Status__c from Promise_to_Pay__c where Billing_Account__c = :ba.Id LIMIT 1];
		List<Case> cases = [select Id, Record_Type_Name__c from Case where Billing_Account__c = :ba.Id];
		
		system.assertEquals(Constants.PaymentPlanStatus_Saved, savedP2P.Status__c);
		system.assertEquals(0, cases.size());
	}
	
	static testmethod void testBeforeInsert_WithActiveP2PInLast6Months_ErrorThrown() {
		
		//Create Custom Setting
		//Collections_Settings__c cs = createCollectionSettings();
		TestHelper.createCollectionSettings(6);
		
		Billing_Account__c ba = new Billing_Account__c(Name = 'Test', CURRENT_OVERDUE__c = 300, Unbilled_Amount__c = 20, Call_Limit__c = 25, 
						Billing_Day_in_Month__c = Date.today().day(), Exposure_Value__c = 120, DAYS_61_90__c = 100);
		insert ba;
		
		Account acc = new Account (Name = 'Test_Acc_1');
        insert acc;
        
        insert new Asset(Name='TestassetName', AccountId=acc.Id, 	Billing_Account__c=ba.id , Status__c = 'ACTIVE');
        
		//Create historical P2P
		Promise_to_Pay__c p2p1 = new Promise_to_Pay__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Open, 
			 Proposed_Payment_Date__c = Date.today().addDays(2), Amount_Due__c = 1000, One_off_Payment__c = 100);
		insert p2p1;
		
		p2p1.Status__c = Constants.PaymentPlanStatus_Closed;
		update p2p1;
		
		// Create new P2P
		Promise_to_Pay__c p2p2 = new Promise_to_Pay__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Open, 
			Proposed_Payment_Date__c = Date.today(), Amount_Due__c = 1000, One_off_Payment__c = 100);
		
		try {
			insert p2p2;
		}
		catch (Exception ex) {
			 System.assert(ex.getMessage().indexOf('A Promise To Pay was setup in the last 6 months') > 0);
		}	
	}
	
	static testmethod void testBeforeInsert_WithExistingActiveP2P_ErrorThrown() {
		
		//Create Custom Setting
		//Collections_Settings__c cs = createCollectionSettings();
		TestHelper.createCollectionSettings(6);
		
		Billing_Account__c ba = new Billing_Account__c(Name = 'Test', CURRENT_OVERDUE__c = 300, Unbilled_Amount__c = 20, Call_Limit__c = 25, 
						Billing_Day_in_Month__c = Date.today().day(), Exposure_Value__c = 120, DAYS_61_90__c = 100);
		insert ba;
		
		Account acc = new Account (Name = 'Test_Acc_1');
        insert acc;
        
        insert new Asset(Name='TestassetName', AccountId=acc.Id, 	Billing_Account__c=ba.id , Status__c = 'ACTIVE');
		
		Promise_to_Pay__c p2p1 = new Promise_to_Pay__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Open, 
			Proposed_Payment_Date__c = Date.today().addDays(2), Amount_Due__c = 1000, One_off_Payment__c = 100);
		insert p2p1;
		
		// Create new P2P
		Promise_to_Pay__c p2p2 = new Promise_to_Pay__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Open, 
			Proposed_Payment_Date__c = Date.today().addDays(2), Amount_Due__c = 1000, One_off_Payment__c = 100);
		
		try {
			insert p2p2;
		}
		catch (Exception ex) {
			 System.assert(ex.getMessage().indexOf('Only 1 Active Promise To Pay can exist for a Billing Account') > 0);
		}	
	}
	
	static testmethod void testBeforeInsert_WithExistingActivePaymentPlan_ErrorThrown() {
		
		//Create Custom Setting
		//Collections_Settings__c cs = createCollectionSettings();
		TestHelper.createCollectionSettings(6);
		
		Billing_Account__c ba = new Billing_Account__c(Name = 'Test', CURRENT_OVERDUE__c = 300, Unbilled_Amount__c = 20, Call_Limit__c = 25, 
						Billing_Day_in_Month__c = Date.today().day(), Exposure_Value__c = 120);
		insert ba;
		
		Account acc = new Account (Name = 'Test_Acc_1');
        insert acc;
        
        insert new Asset(Name='TestassetName', AccountId=acc.Id, 	Billing_Account__c=ba.id , Status__c = 'ACTIVE');
        
		
		Payment_Plan__c pp = new Payment_Plan__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Open, 
							Date_of_First_Installment__c = Date.today());
		insert pp;
		
		// Create new P2P
		Promise_to_Pay__c p2p = new Promise_to_Pay__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Open, 
			 Proposed_Payment_Date__c = Date.today().addDays(2), Amount_Due__c = 1000);
		
		try {
			insert p2p;
		}
		catch (Exception ex) {
			 System.assert(ex.getMessage().indexOf('It is not possible to have a P2P if a Payment Plan is active/open') > 0);
		}	
	}
	
	static Collections_Settings__c createCollectionSettings() {
		Collection_Path__c cp = new Collection_Path__c(Name = 'P2P Path', Active__c = true);
		insert cp; 
		
		Collections_Settings__c cs = new Collections_Settings__c(Approval_Term_Threshold__c = 6, 
																	Payment_Plan_Path__c = 'Payment Plan', //doesn't matter
																	PP_Call_Limit__c = 10,
																	P2P_Path_for_30_60d_Debt__c = cp.Name, //doesn't matter
																	P2P_Path_for_Less_than_30d_Debt__c = cp.Name,
																	PTP_Confirmation_Email_Template_AOL__c = 'A Template 1' , //doesn't matter 
																	PTP_Confirmation_Email_Template_TT__c = 'A Template 2', //doesn't matter
																	PA_Confirmation_Email_Template_AOL__c = 'A Template 3', //doesn't matter
																	PA_Confirmation_Email_Template_TT__c = 'A Template 4'); //doesn't matter;
		insert cs;
		
		return cs;
	}


}