Production/Production/src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Production/Production/src/objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Balance__c</fullName>
        <label>Account Balance</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Account_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Day_in_Month__c</fullName>
        <label>Billing Days in Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CURRENT_OVERDUE__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Current Overdue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Limit__c</fullName>
        <label>Call Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DAYS_121_150__c</fullName>
        <label>DAYS 121-150</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DAYS_151_180__c</fullName>
        <label>DAYS 151-180</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DAYS_181_210__c</fullName>
        <label>DAYS 181-210</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DAYS_211_240__c</fullName>
        <label>DAYS 211-240</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DAYS_31_60__c</fullName>
        <label>DAYS 31-60</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DAYS_61_90__c</fullName>
        <label>DAYS 61-90</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DAYS_91_120__c</fullName>
        <label>DAYS 91-120</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exposure_Value__c</fullName>
        <label>Exposure Value</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNBILLED_AMOUNT__c</fullName>
        <label>Unbilled Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/Production/src/objects/Collection_Path__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag indicates if the Path is active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Collection Path</label>
    <nameField>
        <label>Collection Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Production/Production/src/objects/Collection_Step__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Collection_Path__c</fullName>
        <label>Collection Path</label>
        <referenceTo>Collection_Path__c</referenceTo>
        <relationshipLabel>Collection Steps</relationshipLabel>
        <relationshipName>Collection_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Days_on_this_step__c</fullName>
        <label>Days on this step</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Step_type__c</fullName>
        <label>Step type</label>
        <picklist>
            <picklistValues>
                <fullName>Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disconnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refer to Write off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wait</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Defaulted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>is_Default_Next_Step__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates that the step should be considered as default next step</description>
        <label>is Default Next Step</label>
        <type>Checkbox</type>
    </fields>
    <label>Collection Step</label>
    <nameField>
        <label>Collection Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Production/Production/src/objects/Collections_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Various settings for Collections</description>
    <fields>
        <fullName>Approval_Term_Threshold__c</fullName>
        <description>The number of periods above which a PP will require approval before it is Active/Open.</description>
        <label>Approval Term Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email_Address_for_Extracted_Data__c</fullName>
        <label>Email Address for Extracted Data</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>P2P_Path_for_30_60d_Debt__c</fullName>
        <label>P2P Path for 30 60d Debt</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P2P_Path_for_Less_than_30d_Debt__c</fullName>
        <label>P2P Path for Less than 30d Debt</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P2P_Payment_Days_from_Now_Tolerance__c</fullName>
        <description>This setting holds tolerance for maximum number of days from the setup date to accept payment for P2P</description>
        <label>P2P Payment Days from Now Tolerance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PA_Confirmation_Email_Template_AOL__c</fullName>
        <description>The id of the PP Confirmation Template that is sent as an email to the AOL customer once a PP has been activated and a case created.</description>
        <label>PA Confirmation Email Template AOL</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PA_Confirmation_Email_Template_TT__c</fullName>
        <description>The id of the PP Confirmation Template that is sent as an email to the Talk Talk customer once a PP has been activated and a case created.</description>
        <label>PA Confirmation Email Template TT</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PP_Call_Limit__c</fullName>
        <label>PP Call Limit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PTP_Confirmation_Email_Template_AOL__c</fullName>
        <description>The id of the P2P Confirmation Template that is sent as an email to the AOL customer once a P2P has been activated and a case created.</description>
        <label>PTP Confirmation Email Template AOL</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PTP_Confirmation_Email_Template_TT__c</fullName>
        <description>The id of the P2P Confirmation Template that is sent as an email to the TT customer once a P2P has been activated and a case created.</description>
        <label>PTP Confirmation Email Template TT</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Acceptable_Tolerance__c</fullName>
        <label>Payment Acceptable Tolerance</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Days_from_Now_Tolerance_Oneoff__c</fullName>
        <description>This setting holds Tolerance value for maximum number of days from now when the one off payment is made</description>
        <label>Payment Days from Now Tolerance Oneoff</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Days_from_Now_Tolerance__c</fullName>
        <description>Up to how many days the P2P Proposed Payment Date and the PP First Installment Date can be from today.</description>
        <label>Payment Days from Now Tolerance</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Plan_Path__c</fullName>
        <label>Payment Plan Path</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Collections Settings</label>
</CustomObject>

Production/Production/src/objects/Promise_to_Pay__c.object
<CustomObject>
    <fields>
        <fullName>Account_Balance__c</fullName>
        <formula>Billing_Account__r.Account_Balance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Promise to Pay</relationshipLabel>
        <relationshipName>Promise_to_Pay</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collection_Path__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collection Path</label>
        <referenceTo>Collection_Path__c</referenceTo>
        <relationshipLabel>Promise to Pay</relationshipLabel>
        <relationshipName>Promise_to_Pay</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DAYS_121_150__c</fullName>
        <formula>Billing_Account__r.DAYS_121_150__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DAYS 121-150</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DAYS_151_180__c</fullName>
        <formula>Billing_Account__r.DAYS_151_180__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DAYS 151-180</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DAYS_181_210__c</fullName>
        <formula>Billing_Account__r.DAYS_181_210__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DAYS 181-210</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DAYS_31_60__c</fullName>
        <formula>Billing_Account__r.DAYS_31_60__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DAYS 31-60</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DAYS_61_90__c</fullName>
        <formula>Billing_Account__r.DAYS_61_90__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DAYS 61-90</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DAYS_91_120__c</fullName>
        <formula>Billing_Account__r.DAYS_91_120__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DAYS 91-120</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Promise to Pay</label>
    <nameField>
        <displayFormat>P2P-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promise to Pay</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Production/Production/src/classes/TestHelper.cls
public class TestHelper {
	
	public static void createCollectionSettings(Integer approvalThreshold) {
		
		Collection_Path__c cp_PP = new Collection_Path__c(Name = 'Payment Plan Path', Active__c = true);
		Collection_Path__c cp_P2P_1 = new Collection_Path__c(Name = 'P2P 1', Active__c = true);
		Collection_Path__c cp_P2P_2 = new Collection_Path__c(Name = 'P2P 2', Active__c = true);
		insert new List<Collection_Path__c> {cp_PP, cp_P2P_1, cp_P2P_2}; 
		
		Collection_Step__c step_PP = new Collection_Step__c (name = 'Step2', Collection_Path__c = cp_PP.id, Days_on_this_step__c = 3, 
															Step_type__c = Constants.CollectionStepType_Wait, Sequence__c = 1, is_Default_Next_Step__c = true);
		insert step_PP;
				
		
		//Create Custom Setting 
			String templateName = 'PP&P2P Template'; 

			Collections_Settings__c cs = new Collections_Settings__c(Approval_Term_Threshold__c = approvalThreshold, 
																		Payment_Plan_Path__c = cp_PP.Name,
																		PP_Call_Limit__c = 10,
																		P2P_Path_for_30_60d_Debt__c = cp_P2P_1.Name, //doesn't matter
																		P2P_Path_for_Less_than_30d_Debt__c = cp_P2P_2.Name, //doesn't matter
																		PTP_Confirmation_Email_Template_AOL__c = templateName , 
																		PTP_Confirmation_Email_Template_TT__c = templateName, 
																		PA_Confirmation_Email_Template_AOL__c = templateName, 
																		PA_Confirmation_Email_Template_TT__c = templateName, 
																		Payment_Acceptable_Tolerance__c = 0.95,
																		Payment_Days_from_Now_Tolerance_Oneoff__c = 31,
																		P2P_Payment_Days_from_Now_Tolerance__c = 21,
																		Payment_Days_from_Now_Tolerance__c = 21,
																		Email_Address_for_Extracted_Data__c = 'bla@test.com');		
		try{
			insert cs;
		} catch ( System.DmlException ex){
			// try upserting again 
			try{
				insert cs;
			} catch ( System.DmlException ex1){
				// ignore 
				insert cs;
			} 		
		} 

	}
		
	
	public static Billing_Account__c createBillingAccount() {
		Account acc = new Account (Name = 'Test_Acc_1');
        insert acc;
        
		Contact primaryContact = new Contact (AccountId = acc.Id, LastName = 'Testius', email='test@test.com');
        insert primaryContact;
        
		Billing_Account__c ba = new Billing_Account__c(Name = 'Test', CURRENT_OVERDUE__c = 300, Account_Balance__c = 300, Unbilled_Amount__c = 20, Call_Limit__c = 25, Brand__c = 'AOL',Account_Id__c = acc.id,
														Exposure_Value__c = 120, Primary_Contact__c = primaryContact.Id, Billing_Day_in_Month__c = 2,DAYS_31_60__c  = 0, DAYS_61_90__c  = 0, 
														DAYS_91_120__c  = 0, DAYS_121_150__c  = 0, DAYS_151_180__c  = 0, DAYS_181_210__c  = 0, 
														DAYS_211_240__c  = 0, DAYS_241_270__c  = 0, DAYS_271_300__c  = 0, DAYS_301_330__c  = 0, DAYS_331_360__c = 0);
		insert ba;
		
		ba = [Select  b.UNBILLED_AMOUNT__c, b.Step_Communication_Type__c, 
		b.Reinstate_Flag__c, b.Promise_to_Pay__c, b.Primary_Contact__c, b.Payment_Defaulted__c, b.Payment_Defaulted_Date__c,  
		b.Next_Treatment_Step__c, b.Next_Bill_Date__c, b.Name, b.Monthly_Recurring_Charge__c, b.MRC__c,Total_Over_Due__c,   
		b.LAST_INVOICE_DATE__c, b.In_Collections__c, Account_Id__c,
		b.Id, b.Exposure_Value__c, b.DAYS_91_120__c, b.DAYS_61_90__c, b.DAYS_331_360__c, b.DAYS_31_60__c, b.DAYS_301_330__c, b.DAYS_271_300__c, 
		b.DAYS_241_270__c, b.DAYS_211_240__c, b.DAYS_181_210__c, b.DAYS_151_180__c, b.DAYS_121_150__c, b.Customer_Status__c, b.Current_Treatment_Step__c, 
		b.Current_Treatment_Path__c, b.CreatedDate, b.CreatedById, b.Call_Limit__c, b.CURRENT_OVERDUE__c, b.Brand__c, 
		b.Billing_Day_in_Month__c, b.Billing_Address__c, b.Balance_Date__c, b.Balance_Amt__c, b.Action_Date__c, b.Account_Key__c, b.Account_Balance__c, 
		b.ACQUISITION_CHANNEL__c From Billing_Account__c b where id = :ba.id];
		
		insert new Asset(Name='TestassetName', AccountId=acc.Id, 	Billing_Account__c=ba.id , Status__c = 'ACTIVE');
		
		return ba;
	}
	
	

}