Production/Production/src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

Production/Production/src/objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Day_in_Month__c</fullName>
        <label>Billing Days in Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CURRENT_OVERDUE__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Current Overdue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Limit__c</fullName>
        <label>Call Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Exposure_Value__c</fullName>
        <label>Exposure Value</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Promise_to_Pay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Promise to Pay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UNBILLED_AMOUNT__c</fullName>
        <label>Unbilled Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/Production/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

Production/Production/src/objects/Payment_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Billing_Account__r.Brand__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Call_Limit__c</fullName>
        <formula>Billing_Account__r.Call_Limit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Call Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_of_First_Installment__c</fullName>
        <label>Date of First Installment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Due_Date__c</fullName>
        <description>Holds the Due Date of the last Line Item. Populated by code, required to check if any PPs existed in the last 6 months</description>
        <label>Last Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Preferred_Communication_Method__c</fullName>
        <label>Preferred Communication Method</label>
        <picklist>
            <picklistValues>
                <fullName>Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unbilled_Amount__c</fullName>
        <formula>Billing_Account__r.UNBILLED_AMOUNT__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unbilled Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Production/Production/src/objects/Promise_to_Pay__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Due</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Promise to Pay</relationshipLabel>
        <relationshipName>Promise_to_Pay</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Preferred_Communication_Method__c</fullName>
        <label>Preferred Communication Method</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Letter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Proposed_Payment_Date__c</fullName>
        <label>Proposed Payment Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Promise to Pay</label>
    <nameField>
        <displayFormat>P2P-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promise to Pay</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Production/Production/src/classes/TestPaymentPlanTriggers.cls
@isTest
private class TestPaymentPlanTriggers {
	
	static testmethod void testAfterInsert_WithOpenStatus_CollectionsCaseCreated() {
		
		TestHelper.createCollectionSettings(6);
		
		Billing_Account__c ba = new Billing_Account__c(Name = 'Test', CURRENT_OVERDUE__c = 300, Unbilled_Amount__c = 20, Call_Limit__c = 25, Exposure_Value__c = 120);
		insert ba;
		
		Account acc = new Account (Name = 'Test_Acc_1');
        insert acc;
        
        insert new Asset(Name='TestassetName', AccountId=acc.Id, 	Billing_Account__c=ba.id , Status__c = 'ACTIVE');
		
		Payment_Plan__c pp = new Payment_Plan__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Open, 
							Date_of_First_Installment__c = Date.today(), Preferred_Communication_Method__c = Constants.PreferredCommMethod_Email);
		insert pp;
		
		//Assert
		
		List<Case> cases = [select Id, Record_Type_Name__c from Case where Billing_Account__c = :ba.Id];
		system.assertEquals(1, cases.size());
		system.assertEquals(Constants.CaseRecordType_Collection, cases[0].Record_Type_Name__c);
	}
	
	static testmethod void testAfterInsert_WithSavedStatus_NoCollectionsCaseCreated() {
		
		TestHelper.createCollectionSettings(6);
		
		Billing_Account__c ba = new Billing_Account__c(Name = 'Test', CURRENT_OVERDUE__c = 300, Unbilled_Amount__c = 20, Call_Limit__c = 25, Exposure_Value__c = 120);
		insert ba;
		
		Account acc = new Account (Name = 'Test_Acc_1');
        insert acc;
        
        insert new Asset(Name='TestassetName', AccountId=acc.Id, 	Billing_Account__c=ba.id , Status__c = 'ACTIVE');
		
		Payment_Plan__c pp = new Payment_Plan__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Saved, 
							Date_of_First_Installment__c = Date.today(), Preferred_Communication_Method__c = Constants.PreferredCommMethod_Email);
		insert pp;
		
		//Assert
		
		List<Case> cases = [select Id, Record_Type_Name__c from Case where Billing_Account__c = :ba.Id];
		system.assertEquals(0, cases.size());
	}
	
	/* 
	 * Mimicks approval process of Payment Plan
	 */
	static testmethod void testAfterUpdate_ToOpenStatus_CollectionsCaseCreatedAndEmailSent() {
		
		TestHelper.createCollectionSettings(6);
		
		Billing_Account__c ba = new Billing_Account__c(Name = 'Test', CURRENT_OVERDUE__c = 300, Unbilled_Amount__c = 20, Call_Limit__c = 25, Exposure_Value__c = 120);
		insert ba;
		
		Account acc = new Account (Name = 'Test_Acc_1');
        insert acc;
        
        insert new Asset(Name='TestassetName', AccountId=acc.Id, 	Billing_Account__c=ba.id , Status__c = 'ACTIVE');
		
		Payment_Plan__c pp = new Payment_Plan__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Saved, 
							Date_of_First_Installment__c = Date.today(), Preferred_Communication_Method__c = Constants.PreferredCommMethod_Email);
		insert pp;
		
		pp.Status__c = Constants.PaymentPlanStatus_Open;
		
		Test.startTest();
		update pp;
		Test.stopTest();
		
		//Assert
		
		List<Case> cases = [select Id, Record_Type_Name__c from Case where Billing_Account__c = :ba.Id];
		system.assertEquals(1, cases.size());
		system.assertEquals(Constants.CaseRecordType_Collection, cases[0].Record_Type_Name__c);
	}
	
	static testmethod void testBeforeUpdate_WithOpenOrClosedStatus_CannotBeModified() {
		
		TestHelper.createCollectionSettings(6);
		
		Billing_Account__c ba = new Billing_Account__c(Name = 'Test', CURRENT_OVERDUE__c = 300, Unbilled_Amount__c = 20, Call_Limit__c = 25, Exposure_Value__c = 120);
		insert ba;
		
		Account acc = new Account (Name = 'Test_Acc_1');
        insert acc;
        
        insert new Asset(Name='TestassetName', AccountId=acc.Id, 	Billing_Account__c=ba.id , Status__c = 'ACTIVE');
		
		Payment_Plan__c pp = new Payment_Plan__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Open, 
							Date_of_First_Installment__c = Date.today(), Preferred_Communication_Method__c = Constants.PreferredCommMethod_Email);
		insert pp;
		
		pp.Date_of_First_Installment__c = Date.today().addDays(1);
		
		Test.startTest();
		try {
			update pp;
		}
		catch (Exception ex) {
			 System.assert(ex.getMessage().indexOf('You don\'t have the permission to edit Open or Closed Payment Plans') > 0);
		}
		Test.stopTest();
	}
	
	static testmethod void testBeforeInsert_WithExistingActivePP_ErrorThrown() {
		TestHelper.createCollectionSettings(6);
		
		Billing_Account__c ba = new Billing_Account__c(Name = 'Test', CURRENT_OVERDUE__c = 300, Unbilled_Amount__c = 20, Call_Limit__c = 25, Exposure_Value__c = 120);
		insert ba;
		
		Account acc = new Account (Name = 'Test_Acc_1');
        insert acc;
        
        insert new Asset(Name='TestassetName', AccountId=acc.Id, 	Billing_Account__c=ba.id , Status__c = 'ACTIVE');
		
		//By 'Active' status we mean anything but 'Closed'
		Payment_Plan__c pp1 = new Payment_Plan__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Open, 
							Date_of_First_Installment__c = Date.today(), Preferred_Communication_Method__c = Constants.PreferredCommMethod_Email);
		insert pp1;
		
		Payment_Plan__c pp2 = new Payment_Plan__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Open, 
							Date_of_First_Installment__c = Date.today(), Preferred_Communication_Method__c = Constants.PreferredCommMethod_Email);
		try {
			insert pp2;
		}
		catch (Exception ex) {
			 System.assert(ex.getMessage().indexOf('Only 1 Open, Saved or Pending Approval Payment Plan can exist for a Billing Account') > 0);
		}	
	}
	
	static testmethod void testBeforeInsert_WithActivePPInLast6Months_ErrorThrown() {
		
		TestHelper.createCollectionSettings(6);
		
		Billing_Account__c ba = new Billing_Account__c(Name = 'Test', CURRENT_OVERDUE__c = 300, Unbilled_Amount__c = 20, Call_Limit__c = 25, Exposure_Value__c = 120);
		insert ba;
		
		Account acc = new Account (Name = 'Test_Acc_1');
        insert acc;
        
        insert new Asset(Name='TestassetName', AccountId=acc.Id, 	Billing_Account__c=ba.id , Status__c = 'ACTIVE');
		
		//By 'Active' status we mean anything but 'Closed'
		Payment_Plan__c pp1 = new Payment_Plan__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Closed, 
							Date_of_First_Installment__c = Date.today(), Last_Due_Date__c = Date.today().addDays(-30), Preferred_Communication_Method__c = Constants.PreferredCommMethod_Email);
		insert pp1;
		
		Payment_Plan__c pp2 = new Payment_Plan__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Open, 
							Date_of_First_Installment__c = Date.today(), Preferred_Communication_Method__c = Constants.PreferredCommMethod_Email);
		try {
			insert pp2;
		}
		catch (Exception ex) {
			 System.assert(ex.getMessage().indexOf('A Payment Plan was setup in the last 6 months.') > 0);
		}	
	}
	
	static testmethod void testBeforeInsert_WithExistingActivePromiseToPay_ErrorThrown() {
		
		//Create Custom Setting
		TestHelper.createCollectionSettings(6);
		
		Billing_Account__c ba = new Billing_Account__c(Name = 'Test', Brand__c='AOL', CURRENT_OVERDUE__c = 300, Billing_Day_in_Month__c = Date.today().day(), Unbilled_Amount__c = 20, Call_Limit__c = 25, Exposure_Value__c = 120);
		insert ba;
		
		Account acc = new Account (Name = 'Test_Acc_1');
        insert acc;
        
        insert new Asset(Name='TestassetName', AccountId=acc.Id, 	Billing_Account__c=ba.id , Status__c = 'ACTIVE');
		
		//Create an active P2P
		Promise_to_Pay__c p2p = new Promise_to_Pay__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Open, Proposed_Payment_Date__c = Date.today(), Amount_Due__c = 1000);
		insert p2p;
		
		
		Payment_Plan__c pp = new Payment_Plan__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Open, 
							Date_of_First_Installment__c = Date.today(), Preferred_Communication_Method__c = Constants.PreferredCommMethod_Email);
		try {
			insert pp;
		}
		catch (Exception ex) {
			 System.assert(ex.getMessage().indexOf('It is not possible to have a Payment Plan if a Promise to Pay is active/open') > 0);
		}	
	}

}