Production/Production/src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

Production/Production/src/objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/Production/src/classes/PopulateCLIonContactBatchTest.cls
@isTest
private class PopulateCLIonContactBatchTest {

    static testMethod void testBatch() {
    	Billing_Account__c billingAccount = TestHelper.createBillingAccount();
    	
    	Asset currentAsset1 = new Asset(Name='Test Name1', AccountId=billingAccount.Account_Id__c, Billing_Account__c = billingAccount.id, Status__c='ACTIVE');
        insert currentAsset1; 
        
        Asset currentAsset = new Asset(Name='Test Name', AccountId=billingAccount.Account_Id__c, Billing_Account__c = billingAccount.id, Status__c='ACTIVE');
        insert currentAsset;
    	
    	 Test.StartTest();
    	 PopulateCLIonContactBatch populateCLIonContactBatch = new PopulateCLIonContactBatch();
    	 ID batchprocessid = Database.executeBatch(populateCLIonContactBatch);
    	 Test.StopTest();
    }
}