Production/Production/src/objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Action_Date__c</fullName>
        <label>Action Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Treatment_Path__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Treatment Path</label>
        <referenceTo>Collection_Path__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Treatment_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Treatment Step</label>
        <referenceTo>Collection_Step__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promise_to_Pay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Promise to Pay</label>
        <type>Checkbox</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/Production/src/objects/Collection_Path__c.object
<CustomObject>
    <label>Collection Path</label>
    <nameField>
        <label>Collection Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Production/Production/src/objects/Collection_Step__c.object
<CustomObject>
    <fields>
        <fullName>Collection_Path__c</fullName>
        <label>Collection Path</label>
        <referenceTo>Collection_Path__c</referenceTo>
        <relationshipLabel>Collection Steps</relationshipLabel>
        <relationshipName>Collection_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Days_on_this_step__c</fullName>
        <label>Days on this step</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Step_type__c</fullName>
        <label>Step type</label>
        <picklist>
            <picklistValues>
                <fullName>Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disconnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refer to Write off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wait</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Defaulted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>is_Default_Next_Step__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates that the step should be considered as default next step</description>
        <label>is Default Next Step</label>
        <type>Checkbox</type>
    </fields>
    <label>Collection Step</label>
    <nameField>
        <label>Collection Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Production/Production/src/objects/Payment_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collection_Path__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collection Path</label>
        <referenceTo>Collection_Path__c</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_First_Installment__c</fullName>
        <label>Date of First Installment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposed_Frequency__c</fullName>
        <label>Proposed Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4-Weeks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Proposed_Term__c</fullName>
        <label>Proposed Term (months)</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Use_New_Call_Limit__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Describes whether the New Call Limit was part of the PP calculations</description>
        <label>Use New Call Limit</label>
        <type>Checkbox</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Production/Production/src/objects/Promise_to_Pay__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Due</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Promise to Pay</relationshipLabel>
        <relationshipName>Promise_to_Pay</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collection_Path__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collection Path</label>
        <referenceTo>Collection_Path__c</referenceTo>
        <relationshipLabel>Promise to Pay</relationshipLabel>
        <relationshipName>Promise_to_Pay</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposed_Payment_Date__c</fullName>
        <label>Proposed Payment Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Promise to Pay</label>
    <nameField>
        <displayFormat>P2P-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promise to Pay</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Production/Production/src/classes/TestPaymentPlanAndP2PClosureBatch.cls
@isTest
private class TestPaymentPlanAndP2PClosureBatch {
	
	public static testmethod void testBatch_WithAccountWithPaymentPlanInFinalStep_PPClosed(){
		
		TestHelper.createCollectionSettings(6);
		
		//One BA with an open PP
		Billing_Account__c ba = TestHelper.createBillingAccount();
		
		Payment_Plan__c pp = new Payment_Plan__c(Billing_Account__c = ba.Id, Date_of_First_Installment__c = Date.today(), Use_New_Call_Limit__c = false, 
			Proposed_Term__c = '1', Proposed_Frequency__c = 'Monthly', Status__c = Constants.PaymentPlanStatus_Open);
		insert pp;
		
		//Createb PP's final Step
		Collection_Path__c ppPath = [select Id from Collection_Path__c where Name = 'Payment Plan Path'];
		Collection_Step__c finalStep_PP = new Collection_Step__c (name = Constants.CompletionStepName_PaymentPlan, Collection_Path__c = ppPath.id, Days_on_this_step__c = 3, 
															Step_type__c = Constants.CollectionStepType_Wait, Sequence__c = 2, is_Default_Next_Step__c = false);
		insert finalStep_PP;
		
		system.debug(finalStep_PP.Collection_Path__c + ' - ' + ba.Current_Treatment_Path__c);
		
		ba.Current_Treatment_Path__c = ppPath.Id;
		ba.Action_Date__c = Date.today();
		ba.Current_Treatment_Step__c = finalStep_PP.Id;
		update ba;
		
		//Now run batch
		
		Test.startTest();
		
		PaymentPlanAndP2PClosureBatch testBatch = new PaymentPlanAndP2PClosureBatch();
		ID testBatchPID = Database.executeBatch(testBatch); 	
		
		Test.stopTest();
		
		//Retrieve and check PP closed
		Payment_Plan__c retrievedPP = [select Status__c from Payment_Plan__c where Id = :pp.Id];
		system.assertEquals(Constants.PaymentPlanStatus_Closed, retrievedPP.Status__c);
	}
		
	public static testmethod void testBatch_WithAccountWithP2PInFinalStep_P2PClosed(){
		
		TestHelper.createCollectionSettings(6);
		
		// Another BA with an open P2P
		Billing_Account__c ba2 = TestHelper.createBillingAccount();
		Promise_to_Pay__c p2p = new Promise_to_Pay__c(Billing_Account__c = ba2.Id, Status__c = Constants.PaymentPlanStatus_Open, 
						Proposed_Payment_Date__c = Date.today().addDays(2), Amount_Due__c = 1000);
		insert p2p;
		
		//Createb P2P's final Step
		Collection_Path__c p2pPath = [select Id from Collection_Path__c where Name = 'P2P 1'];
		Collection_Step__c finalStep_P2P = new Collection_Step__c (name = Constants.CompletionStepName_PromiseToPay, Collection_Path__c = p2pPath.id, Days_on_this_step__c = 3, 
															Step_type__c = Constants.CollectionStepType_Wait, Sequence__c = 2, is_Default_Next_Step__c = false);
		insert finalStep_P2P;
		
		ba2.Current_Treatment_Path__c = p2pPath.Id;
		ba2.Action_Date__c = Date.today();
		ba2.Current_Treatment_Step__c = finalStep_P2P.Id;
		update ba2;
		
		//Now run batch
		
		Test.startTest();
		
		PaymentPlanAndP2PClosureBatch testBatch = new PaymentPlanAndP2PClosureBatch();
		ID testBatchPID = Database.executeBatch(testBatch); 	
		
		Test.stopTest();
		
		//Retrieve and check P2P closed
		Promise_to_Pay__c retrievedP2P = [select Status__c from Promise_to_Pay__c where Id = :p2p.Id];
		system.assertEquals(Constants.PaymentPlanStatus_Closed, retrievedP2P.Status__c);
	}

}