Production/Production/src/objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Action_Date__c</fullName>
        <label>Action Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Collection_Paused__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Collection Paused</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Treatment_Path__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Treatment Path</label>
        <referenceTo>Collection_Path__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Treatment_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Treatment Step</label>
        <referenceTo>Collection_Step__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>In_Collections__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Collections</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Next_Treatment_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Treatment Step</label>
        <referenceTo>Collection_Step__c</referenceTo>
        <relationshipLabel>Billing Accounts (Next Step)</relationshipLabel>
        <relationshipName>Billing_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Defaulted_Date__c</fullName>
        <label>Payment Defaulted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Defaulted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Payment Defaulted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Promise_to_Pay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Promise to Pay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reinstate_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reinstate Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Step_Communication_Type__c</fullName>
        <label>Step Communication Type</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/Production/src/objects/Promise_to_Pay__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Promise to Pay</relationshipLabel>
        <relationshipName>Promise_to_Pay</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promise to Pay</label>
    <nameField>
        <displayFormat>P2P-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promise to Pay</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Production/Production/src/classes/CollectionStepUpdateBatch.cls
/**
    This class acts as the step monitor.
    It looks at all the tasks that are due to be executed and move to next step
*/

public with sharing class CollectionStepUpdateBatch implements Database.Batchable<sObject>, Schedulable {

    public void execute(SchedulableContext scMain) {
        CollectionStepUpdateBatch batch = new CollectionStepUpdateBatch();
        Database.executeBatch(batch, 200);
    }

   public CollectionStepUpdateBatch(){}

   public Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(query);
   }


    // execute method will get the current step and based on the step selected ... 
    // it will update the account with next step 
   public void execute(Database.BatchableContext BC, List<sObject> collectionAccounts){
    
    List<CollectionAccountInfo> colAccounts = new List<CollectionAccountInfo>();    
        
    
      
        // actual processing
        for ( sObject actSObject : collectionAccounts ){
            Billing_Account__c act = ( Billing_Account__c )actSObject;
        
            if( act != null && act.Current_Treatment_Path__c != null && act.Current_Treatment_Step__c != null ){
                colAccounts.add ( new CollectionAccountInfo( act ) );
            }
        }
        
    StepHandler.moveStepsInBulk ( colAccounts );        
   }

   public void finish(Database.BatchableContext BC){
    //some logic will come here
   }
   
   
    private String query{
        get{
            return ' Select b.Step_Communication_Type__c, b.Reinstate_Flag__c, b.Promise_to_Pay__c, b.Payment_Defaulted__c, b.Payment_Defaulted_Date__c, '+
                            ' b.Collection_Paused__c, b.Next_Treatment_Step__c, b.In_Collections__c, b.Current_Treatment_Step__c, b.Current_Treatment_Path__c, b.Action_Date__c ' +
                            ' From Billing_Account__c b '+ 
                    ' Where b.Action_Date__c <= TODAY ';
        }
    }

}