Production/Production/src/objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Promise_to_Pay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Promise to Pay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Over_Due__c</fullName>
        <formula>CURRENT_OVERDUE__c +  DAYS_31_60__c +  DAYS_61_90__c +  DAYS_91_120__c +  DAYS_121_150__c +  DAYS_151_180__c +  DAYS_181_210__c +  DAYS_211_240__c +  DAYS_241_270__c +  DAYS_271_300__c +  DAYS_301_330__c +  DAYS_331_360__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Over Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNBILLED_AMOUNT__c</fullName>
        <label>Unbilled Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/Production/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

Production/Production/src/objects/Payment_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_First_Installment__c</fullName>
        <label>Date of First Installment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Due_Date__c</fullName>
        <description>Holds the Due Date of the last Line Item. Populated by code, required to check if any PPs existed in the last 6 months</description>
        <label>Last Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MRC1__c</fullName>
        <label>MRC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>New_Call_Limit__c</fullName>
        <defaultValue>$Setup.Collections_Settings__c.PP_Call_Limit__c</defaultValue>
        <label>New Call Limit</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Number_of_Installments__c</fullName>
        <label>Number of Installments</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>One_off_Payment__c</fullName>
        <defaultValue>0</defaultValue>
        <label>One off Payment</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <formula>Billing_Account__r.Payment_Method_Desc__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Method</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Communication_Method__c</fullName>
        <label>Preferred Communication Method</label>
        <picklist>
            <picklistValues>
                <fullName>Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Proposed_Frequency__c</fullName>
        <label>Proposed Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4-Weeks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Proposed_Term__c</fullName>
        <label>Proposed Term (months)</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unbilled_Amount__c</fullName>
        <formula>Billing_Account__r.UNBILLED_AMOUNT__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unbilled Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Use_New_Call_Limit__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Describes whether the New Call Limit was part of the PP calculations</description>
        <label>Use New Call Limit</label>
        <type>Checkbox</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Production/Production/src/objects/Payment_Plan_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <formula>Amount__c -  Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <formula>Payment_Plan__r.Billing_Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Payment Plan Lines</relationshipLabel>
        <relationshipName>Payment_Plan_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Plan Line Item</label>
    <nameField>
        <label>Payment Plan Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plan Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Production/Production/src/objects/Promise_to_Pay__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Due</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Promise to Pay</relationshipLabel>
        <relationshipName>Promise_to_Pay</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>One_off_Payment__c</fullName>
        <defaultValue>0</defaultValue>
        <label>One off Payment</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <formula>Billing_Account__r.Payment_Method_Desc__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Method</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Communication_Method__c</fullName>
        <label>Preferred Communication Method</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Letter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Proposed_Payment_Date__c</fullName>
        <label>Proposed Payment Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Over_Due__c</fullName>
        <formula>Billing_Account__r.Total_Over_Due__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Over Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Promise to Pay</label>
    <nameField>
        <displayFormat>P2P-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promise to Pay</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Production/Production/src/classes/TestPaymentPlanController.cls
@isTest
public class TestPaymentPlanController {
    
    static testMethod void createNewPP_NoApproval_CanSave() {
        
        TestHelper.createCollectionSettings(6);
        
        Billing_Account__c ba = TestHelper.createBillingAccount();
        
        Payment_Plan__c pp = new Payment_Plan__c(Billing_Account__c = ba.Id, Date_of_First_Installment__c = Date.today(), Use_New_Call_Limit__c = false);
        
        //Setup page params
        Apexpages.currentPage().getParameters().put('billAccountId', ba.Id);
        
        ApexPages.Standardcontroller strctrl = new ApexPages.Standardcontroller(pp);
        PaymentPlanController customCtrl = new PaymentPlanController(strctrl);
        
        system.assert(!customCtrl.planProduced);
        system.assert(!customCtrl.isReadOnlyMode);
        system.assert(!customCtrl.isExistingPP);
        system.assert(customCtrl.canSave);
        
        //Make selections and calculate payments
        pp.Date_of_First_Installment__c = Date.valueOf ('2013-11-04');
        pp.New_Call_Limit__c = 100;
        pp.Use_New_Call_Limit__c = false;
        pp.One_off_Payment__c = 50;
        pp.Proposed_Frequency__c = 'Weekly';
        pp.Number_of_Installments__c = 8;
        pp.MRC1__c = 2.00;
        
        customCtrl.calculatePayments();
        system.assert(customCtrl.planProduced);
        system.assert(customCtrl.ppItems.size() > 0);
        system.assert(customCtrl.ppItems[0].Due_Date__c == Common.getNextWorkingDay(pp.Date_of_First_Installment__c));
        system.assert(customCtrl.ppItems[0].Amount__c != null);
        
        system.assert(customCtrl.ppItems[customCtrl.ppItems.size()-1].Due_Date__c <= pp.Date_of_First_Installment__c.addMonths(2));
        system.assert(customCtrl.ppItems[customCtrl.ppItems.size()-1].Amount__c != null);
        
        Decimal mrc = 2.00;
        Integer mrcMultiplier = 1; // as it will be just one month included
         
        Decimal totalDue = (ba.Total_Over_Due__c - pp.One_off_Payment__c + ba.Unbilled_Amount__c + (mrcMultiplier * mrc));
                                    
        Decimal totalInstallmentsAmount = 0;
        for (Payment_Plan_Line_Item__c li : customCtrl.ppItems) {
            totalInstallmentsAmount += li.Amount__c;
        }
        
        //system.assertEquals(totalDue, totalInstallmentsAmount);
        
        customCtrl.savePP();
        
        customCtrl.cancel();
        
        // Retrieve and assert
        Payment_Plan__c savedPP = [select Billing_Account__c, Date_of_First_Installment__c, Last_Due_Date__c, New_Call_Limit__c, Number_of_Installments__c,
                                        One_off_Payment__c, Payment_Method__c, Proposed_Frequency__c, Status__c,
                                        (select Id, Name, Amount__c, Due_Date__c from Payment_Plan_Lines__r order by Due_Date__c asc)
                                    from Payment_Plan__c where Billing_Account__c = :ba.Id];
                                    
        List<Case> collectionCase = [select Record_Type_Name__c, Status  from Case where Billing_Account__c = :ba.Id];
                                    
        
        system.assertEquals(Date.valueOf ('2013-11-04'), savedPP.Date_of_First_Installment__c);
        system.assertEquals(savedPP.Payment_Plan_Lines__r[savedPP.Payment_Plan_Lines__r.size()-1].Due_Date__c, savedPP.Last_Due_Date__c);
        system.assertEquals(100, savedPP.New_Call_Limit__c);
        system.assert(savedPP.Number_of_Installments__c > 0);
        system.assertEquals(50, savedPP.One_off_Payment__c);
        system.assertEquals('Weekly', savedPP.Proposed_Frequency__c);
        system.assertEquals(8, savedPP.Number_of_Installments__c);
        system.assertEquals('Open', savedPP.Status__c);
        
        system.assertEquals('New', collectionCase[0].Status);
        system.assertEquals(Constants.CaseRecordType_Collection, collectionCase[0].Record_Type_Name__c);
        
    }
    
    static testMethod void createNewPP_WithApproval_CanSave() {
        
        TestHelper.createCollectionSettings(6);
                
        Billing_Account__c ba = TestHelper.createBillingAccount();
        
        Payment_Plan__c pp = new Payment_Plan__c(Billing_Account__c = ba.Id);
        
        //Setup page params
        Apexpages.currentPage().getParameters().put('billAccountId', ba.Id);
        
        ApexPages.Standardcontroller strctrl = new ApexPages.Standardcontroller(pp);
        PaymentPlanController customCtrl = new PaymentPlanController(strctrl);
        
        system.assert(!customCtrl.planProduced);
        system.assert(!customCtrl.isReadOnlyMode);
        system.assert(!customCtrl.isExistingPP);
        system.assert(customCtrl.canSave);
        
        //Make selections and calculate payments
        pp.Date_of_First_Installment__c = Date.valueOf('2013-11-04');
        pp.New_Call_Limit__c = 100;
        pp.Use_New_Call_Limit__c = true;
        pp.One_off_Payment__c = 50;
        pp.Proposed_Frequency__c = 'Monthly';
        pp.Number_of_Installments__c = 8;
        pp.MRC1__c = 2.00;
                
        customCtrl.calculatePayments();
        system.assert(customCtrl.planProduced);
        system.assert(customCtrl.ppItems.size() > 0);
        system.assert(customCtrl.ppItems[0].Due_Date__c == Common.getNextWorkingDay (pp.Date_of_First_Installment__c));
        system.assert(customCtrl.ppItems[0].Amount__c != null);
        
        system.assert(customCtrl.ppItems[customCtrl.ppItems.size()-1].Due_Date__c <= pp.Date_of_First_Installment__c.addMonths(Integer.valueof(pp.Number_of_Installments__c)));
        
        system.assert(customCtrl.ppItems[customCtrl.ppItems.size()-1].Amount__c != null);
        
        Decimal mrcMultiplier = 7;
        Decimal totalDue = (ba.Total_Over_Due__c - pp.One_off_Payment__c + ba.Unbilled_Amount__c + (mrcMultiplier * pp.MRC1__c ) +  
                (mrcMultiplier * Integer.valueOf(pp.New_Call_Limit__c)) );
        
        Decimal totalInstallments = 0;
        for (Payment_Plan_Line_Item__c li : customCtrl.ppItems) {
            totalInstallments += li.Amount__c;
        }
        
        //system.assertEquals(totalDue, totalInstallments);
        
        customCtrl.savePP();
        
        customCtrl.cancel();
        
        // Retrieve and assert
        Payment_Plan__c savedPP = [select Billing_Account__c, Date_of_First_Installment__c, Last_Due_Date__c, New_Call_Limit__c, Number_of_Installments__c,
                                        One_off_Payment__c, Payment_Method__c, Proposed_Frequency__c, Status__c,
                                        (select Id, Name, Amount__c, Due_Date__c from Payment_Plan_Lines__r order by Due_Date__c asc)
                                    from Payment_Plan__c where Billing_Account__c = :ba.Id];
                                    
        List<Case> collectionCases = [select Record_Type_Name__c, Status  from Case where Billing_Account__c = :ba.Id];
                                    
        
        system.assertEquals(Date.valueOf ('2013-11-04'), savedPP.Date_of_First_Installment__c);
        system.assertEquals(savedPP.Payment_Plan_Lines__r[savedPP.Payment_Plan_Lines__r.size()-1].Due_Date__c, savedPP.Last_Due_Date__c);
        system.assertEquals(100, savedPP.New_Call_Limit__c);
        system.assert(savedPP.Number_of_Installments__c > 0);
        system.assertEquals(50, savedPP.One_off_Payment__c);
        system.assertEquals('Monthly', savedPP.Proposed_Frequency__c);
        system.assertEquals(pp.Number_of_Installments__c, savedPP.Number_of_Installments__c);
        system.assertEquals(Constants.PaymentPlanStatus_PendingApproval, savedPP.Status__c);
        
        system.assert(collectionCases.size() == 0);
        
        //Submit for approval
        //customCtrl.submitForApproval();
    }
    
    static testMethod void createNewPP_WithApproval_CannotSave() {
        
        TestHelper.createCollectionSettings(6);
        
        Billing_Account__c ba = TestHelper.createBillingAccount();
        
        //Create an active P2P
        Promise_to_Pay__c p2p = new Promise_to_Pay__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Open, Proposed_Payment_Date__c = Date.today(), Amount_Due__c = 1000);
        insert p2p;
        
        Payment_Plan__c pp = new Payment_Plan__c(Billing_Account__c = ba.Id);
        
        //Setup page params
        Apexpages.currentPage().getParameters().put('billAccountId', ba.Id);
        
        ApexPages.Standardcontroller strctrl = new ApexPages.Standardcontroller(pp);
        PaymentPlanController customCtrl = new PaymentPlanController(strctrl);
        
        system.assert(!customCtrl.planProduced);
        system.assert(!customCtrl.isReadOnlyMode);
        system.assert(!customCtrl.isExistingPP);
        system.assert(!customCtrl.canSave);
        system.assertEquals(customCtrl.notClosedPPReason, customCtrl.cannotSaveReason);
        
        //Make selections and calculate payments
        pp.Date_of_First_Installment__c = Date.today();
        pp.New_Call_Limit__c = 100;
        pp.Use_New_Call_Limit__c = true;
        pp.One_off_Payment__c = ba.Total_Over_Due__c + 100;  // TRY
        pp.Proposed_Frequency__c = 'Weekly';
        pp.Number_of_Installments__c = 8;
        
        
        // Attempt to calc when entering a One off greater to Balance
        customCtrl.calculatePayments();
        
        system.assert(!customCtrl.planProduced);
        
        /*
        ApexPages.Message[] msgs = ApexPages.getMessages();
        Boolean found=false;
        for (ApexPages.Message msg : msgs)
        {
           if (msg.getSummary().contains('The One off Payment cannot exceed the overdue amount'))
           {
              found=true;
           }
        }
        
        System.assert(found);
        */
        /*
        //Now enter a valid One off payment
        pp.One_off_Payment__c = ba.Total_Over_Due__c - 100; 
        
        customCtrl.calculatePayments();
        system.assert(customCtrl.planProduced);
        
        //Save
        customCtrl.savePP(); //This should display an error and exit
        
        msgs = ApexPages.getMessages();
        found=false;
        for (ApexPages.Message msg : msgs)
        {
           if (msg.getSummary().contains('error'))
           {
              found=true;
           }
        }
        
        System.assert(found);
                
        customCtrl.cancel();
        
        // Retrieve and assert
        List<Payment_Plan__c> savedPPs = [select Billing_Account__c, Date_of_First_Installment__c, Last_Due_Date__c, New_Call_Limit__c, Number_of_Installments__c,
                                        One_off_Payment__c, Payment_Method__c, Proposed_Frequency__c, Proposed_Term__c, Status__c,
                                        (select Id, Name, Amount__c, Due_Date__c from Payment_Plan_Lines__r order by Due_Date__c asc)
                                    from Payment_Plan__c where Billing_Account__c = :ba.Id];
                                            
        system.assertEquals(0, savedPPs.size());
        */
    }
    
    static testMethod void viewExistingSavedPP_AssertEditableMode() {
        
        TestHelper.createCollectionSettings(6);
        
        Billing_Account__c ba = TestHelper.createBillingAccount();
        
        Payment_Plan__c pp = new Payment_Plan__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Saved, 
                            Date_of_First_Installment__c = Date.today(),  Number_of_Installments__c = 3);
        insert pp;
        
        Payment_Plan_Line_Item__c li = new Payment_Plan_Line_Item__c(Payment_Plan__c = pp.Id, Amount__c = 20, Due_Date__c = Date.today());
        insert li;
        
        //DON'T Setup page params
        
        ApexPages.Standardcontroller strctrl = new ApexPages.Standardcontroller(pp);
        PaymentPlanController customCtrl = new PaymentPlanController(strctrl);
        
        system.assert(!customCtrl.planProduced);
        system.assert(!customCtrl.isReadOnlyMode);
        system.assert(customCtrl.isExistingPP);
        system.assert(customCtrl.canSave);
    }
    
    static testMethod void viewExistingOpenPP_AssertReadOnlyMode() {
        
        TestHelper.createCollectionSettings(6);
                
        Billing_Account__c ba = TestHelper.createBillingAccount();
        
        Payment_Plan__c pp = new Payment_Plan__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Open,
                    Date_of_First_Installment__c = Date.today(), Preferred_Communication_Method__c = Constants.PreferredCommMethod_Email,
                    Number_of_Installments__c = 1);
        insert pp;
        
        Payment_Plan_Line_Item__c li = new Payment_Plan_Line_Item__c(Payment_Plan__c = pp.Id, Amount__c = 20, Due_Date__c = Date.today());
        insert li;
        
        //DON'T Setup page params
        
        ApexPages.Standardcontroller strctrl = new ApexPages.Standardcontroller(pp);
        PaymentPlanController customCtrl = new PaymentPlanController(strctrl);
        
        system.assert(!customCtrl.planProduced);
        system.assert(customCtrl.isReadOnlyMode);
        system.assert(customCtrl.isExistingPP);
    }

}