Production/Production/src/objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action_Date__c</fullName>
        <label>Action Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Step__c</fullName>
        <label>Current Step</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>In_Collections__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Collections</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Next_Step__c</fullName>
        <label>Next Step</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Treatment_Path__c</fullName>
        <label>Treatment Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/Production/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Production/Production/src/classes/TestStepHandler.cls
/**

	This is a class to test functionality under StepHandler

*/

@isTest
private class TestStepHandler {
/*
    static testMethod void createStepTest() {
		

        // create customer account 
        Account customer = new Account (name = 'testCustomer');
        insert customer;
        
        // create BillingAccount  
        List<Billing_Account__c> accounts = new List<Billing_Account__c>();
        Billing_Account__c billingAccount = new Billing_Account__c (
        		name = 'test', Account_Id__c = customer.id, In_Collections__c = true 
        		//, Treatment_Path__c = 'High', current_step__c ='Comm1'
        		, 
        		Action_Date__c = system.today(),
				Next_Step__c = 'Comm2'
        		);
        accounts.add(billingAccount);

        Billing_Account__c billingAccount2 = new Billing_Account__c (
        		name = 'test', Account_Id__c = customer.id, In_Collections__c = true 
        		//, Treatment_Path__c = 'High', current_step__c ='Comm1'
        		, 
        		Action_Date__c = system.today()
        		);
        accounts.add(billingAccount2);	
        
        Billing_Account__c billingAccount3 = new Billing_Account__c (
        		name = 'test', Account_Id__c = customer.id, In_Collections__c = true 
        		//, Treatment_Path__c = 'High', current_step__c ='Comm1'
        		, 
        		Action_Date__c = system.today(), Next_Step__c = 'Comm2'
        		);
        accounts.add(billingAccount3);	


        Billing_Account__c billingAccount4 = new Billing_Account__c (
        		name = 'test', Account_Id__c = customer.id, In_Collections__c = true 
        		//, Treatment_Path__c = 'High', current_step__c ='Comm1'
        		, 
        		Action_Date__c = system.today(), Next_Step__c = 'Comm2'
        		);
        accounts.add(billingAccount4);	
        
                	
        insert accounts;
        
        // create a case
        //Case cs = new Case (Account = customer.id,)
        
        
        //verify default step move
        StepHandler.moveStep(billingAccount, null, null, null);
        StepHandler.moveStep(billingAccount2, null, null, null);
         StepHandler.moveStep(billingAccount3, null, 'customStep', null);
         StepHandler.moveStep(billingAccount4, null, null, 'customStepByAction');
        
        List<Billing_Account__c> billacts1 = [SELECT current_step__c from Billing_Account__c where Id = :billingAccount.id Limit 1 ];
		system.assertEquals(billacts1.size() , 1);
		system.assertEquals(billacts1[0].current_step__c , 'Comm2');


        //verify step move to first step		
        List<Billing_Account__c> billacts2 = [SELECT current_step__c from Billing_Account__c where Id = :billingAccount2.id LIMIT 1];
		system.assertEquals(billacts2.size() , 1);
		system.assertEquals(billacts2[0].current_step__c , 'firstStep');


        //verify step move to manual step		
        List<Billing_Account__c> billacts3 = [SELECT current_step__c from Billing_Account__c where Id = :billingAccount3.id LIMIT 1];
		system.assertEquals(billacts3.size() , 1);
		system.assertEquals(billacts3[0].current_step__c , 'customStep');

        //verify step move to manual step		
        List<Billing_Account__c> billacts4 = [SELECT current_step__c from Billing_Account__c where Id = :billingAccount4.id LIMIT 1];
		system.assertEquals(billacts4.size() , 1);
		system.assertEquals(billacts4[0].current_step__c , 'customStepByAction');


        /*
        
                StepHandler.moveStep(billingAccount, null, null);
        StepHandler.moveStep(billingAccount2, null, null);
        
        List<Billing_Account__c> billacts = [SELECT current_step__c, Id from Billing_Account__c where Account_Id__c = :customer.id ];
		system.assertEquals(billacts.size() , 2);
		
		//TODO is there any better way of doing this?
		for (Billing_Account__c billAct : billacts){
			if (billAct.id == billingAccount.id){
				//verify default step move
				system.assertEquals(billacts[0].current_step__c , 'Comm2');
			}else if (billAct.id == billingAccount2.id){
			    //verify step move manual
				system.assertEquals(billacts[0].current_step__c , 'firstStep');
			}

		}
		
		*/
        
    //}
}