Production/Production/src/objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Promise_to_Pay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Promise to Pay</label>
        <type>Checkbox</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/Production/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Collection</fullName>
        <active>true</active>
        <businessProcess>R6Service__SocialMedia</businessProcess>
        <label>Collection</label>
    </recordTypes>
</CustomObject>

Production/Production/src/objects/Collection_Path__c.object
<CustomObject>
    <label>Collection Path</label>
    <nameField>
        <label>Collection Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Production/Production/src/objects/Payment_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collection_Path__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collection Path</label>
        <referenceTo>Collection_Path__c</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Production/Production/src/objects/Promise_to_Pay__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Promise to Pay</relationshipLabel>
        <relationshipName>Promise_to_Pay</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collection_Path__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collection Path</label>
        <referenceTo>Collection_Path__c</referenceTo>
        <relationshipLabel>Promise to Pay</relationshipLabel>
        <relationshipName>Promise_to_Pay</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Promise to Pay</label>
    <nameField>
        <displayFormat>P2P-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promise to Pay</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Production/Production/src/classes/PaymentPlanPromise2PayHelper.cls
public with sharing class PaymentPlanPromise2PayHelper {

	public static void closePaymentPlan ( Id ppId ){	
		closePaymentPlansInBulk ( new List<Id> { ppId }, false );	
	}	
	
	public static void closePaymentPlan ( Id ppId, boolean forceClose ){	
		closePaymentPlansInBulk ( new List<Id> { ppId }, forceClose );	
	}

	public static void closePaymentPlansInBulk ( List<Id> Ids ){
		closePaymentPlansInBulk ( Ids, false );	
	}

	public static void closePaymentPlansInBulk ( List<Id> Ids, boolean forceClose ){	
			List <Payment_Plan__c> plansToUpdate = new List<Payment_Plan__c>();
			List <CollectionAccountInfo> colAccounts = new List<CollectionAccountInfo> ();
			system.debug('------closePaymentPlansInBulk------Ids.size--' + Ids.size() + '---');
	        List<Payment_Plan__c> plans = database.query('select Id, Status__c, Billing_Account__c, ' + 
        												SObjectHelper.getFieldListForSOQL('Billing_Account__c', 'Billing_Account__r.') + 
        												' from Payment_Plan__c where Id = :Ids');
	
			if( plans != null && plans.size() > 0){
				for ( Payment_Plan__c plan : plans ) {	        	
		            //Close Plan
		            plan.Status__c = 'Closed';		            
		            plansToUpdate.add ( plan );
		            //Also Close the Collection Case & Clear History
		            colAccounts.add( new  CollectionAccountInfo(plan.Billing_Account__r, plan.Collection_Path__c, true) );
				}
				// update all the plans
		        
		        if (forceClose){
		            SystemUpdateFlags.NoCheckForPaymentPlanModification = true;
			        update plansToUpdate;
		            SystemUpdateFlags.NoCheckForPaymentPlanModification = false;

		        	PathHandler.exitPathsInBulk( colAccounts );
		        }else {
		        	StepHandler.moveStepsInBulk( colAccounts );
		        }
			}
	}
	


	public static void closePromiseToPay ( Id ppId ){	
		closePromiseToPaysInBulk ( new List<Id> { ppId }, false );	
	}	
	
	public static void closePromiseToPay ( Id ppId, boolean forceClose ){	
		closePromiseToPaysInBulk ( new List<Id> { ppId }, forceClose );	
	}

	public static void closePromiseToPaysInBulk ( List<Id> Ids ){
		system.debug ( '££££££££££££££££££££ 3' );
		closePromiseToPaysInBulk ( Ids, false );	
	}
	
	public static void closePromiseToPaysInBulk ( List<Id> Ids, boolean forceClose ){	
			List <Promise_to_Pay__c> promisesToUpdate = new List<Promise_to_Pay__c>();
			List <CollectionAccountInfo> colAccounts = new List<CollectionAccountInfo> ();
			system.debug ( '££££££££££££££££££££ 4' );
        List<Promise_to_Pay__c> promises = database.query('select Id, Status__c, Billing_Account__c, ' + 
        												SObjectHelper.getFieldListForSOQL('Billing_Account__c', 'Billing_Account__r.') + 
        												' from Promise_to_Pay__c where Id = :Ids');
	
			if( promises != null && promises.size() > 0){
				for ( Promise_to_Pay__c promise : promises ) {	        	
		            //Close Plan
system.debug ( '££££££££££££££££££££ 5' );
		            promise.Status__c = 'Closed';
		            promisesToUpdate.add ( promise );
		            
		            //Also Close the Collection Case & Clear History
		            CollectionAccountInfo colInfo = new  CollectionAccountInfo(promise.Billing_Account__r, promise.Collection_Path__c, true);
		            colInfo.action = Constants.CollectionStepAction_Payment; 
		            colAccounts.add( colInfo );
				}

		        if (forceClose){
		        	system.debug ( '££££££££££££££££££££ 6.1' );
					// update all the plans
		            SystemUpdateFlags.NoCheckForPaymentPlanModification = true;	
			        update promisesToUpdate;
		            SystemUpdateFlags.NoCheckForPaymentPlanModification = false;
		        	
		        	PathHandler.exitPathsInBulk( colAccounts );
		        }else {
		        	system.debug ( '££££££££££££££££££££ 6.2' );
		        	
		        	StepHandler.moveStepsInBulk( colAccounts );
		        }
		        
			}
	}	

}