Production/Production/src/objects/Billing_Account__c.object
<CustomObject>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/Production/src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Payment_ID__c</fullName>
        <externalId>true</externalId>
        <label>Payment ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Payment_Source_Code__c</fullName>
        <label>Payment Source Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Production/Production/src/objects/Payment_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_First_Installment__c</fullName>
        <label>Date of First Installment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Installments__c</fullName>
        <label>Number of Installments</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Preferred_Communication_Method__c</fullName>
        <label>Preferred Communication Method</label>
        <picklist>
            <picklistValues>
                <fullName>Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Production/Production/src/objects/Payment_Plan_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Paid__c</fullName>
        <defaultValue>0.000</defaultValue>
        <label>Amount Paid</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <formula>Payment_Plan__r.Billing_Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Payment_Due_Date__c</fullName>
        <description>Calculated by code when items are being generated</description>
        <label>Next Payment Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Payment Plan Lines</relationshipLabel>
        <relationshipName>Payment_Plan_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Plan Line Item</label>
    <nameField>
        <label>Payment Plan Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plan Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Production/Production/src/classes/TestPaymentPlanLineItemTriggers.cls
@isTest
private class TestPaymentPlanLineItemTriggers {
	
	static testmethod void afterUpdate_AmountPaidInPart_processPaymentReceived() {
		
		TestHelper.createCollectionSettings(6);
		
		Billing_Account__c ba = TestHelper.createBillingAccount();
		
		Payment_Plan__c pp = new Payment_Plan__c(Billing_Account__c = ba.Id, Status__c = Constants.PaymentPlanStatus_Open, 
							Date_of_First_Installment__c = Date.today(), Preferred_Communication_Method__c = Constants.PreferredCommMethod_Email,
							Number_of_Installments__c = 3);
		insert pp;
		
		List<Payment_Plan_Line_Item__c> pplis = new List<Payment_Plan_Line_Item__c>();
		
		pplis.add(new Payment_Plan_Line_Item__c(Payment_Plan__c = pp.Id, Name = 'Payment 1', Amount__c = 120, Due_Date__c = Date.today(), Next_Payment_Due_Date__c = Date.today().addDays(15)));
		pplis.add(new Payment_Plan_Line_Item__c(Payment_Plan__c = pp.Id, Name = 'Payment 2', Amount__c = 120, Due_Date__c = Date.today().addDays(15), Next_Payment_Due_Date__c = Date.today().addDays(30)));
		pplis.add(new Payment_Plan_Line_Item__c(Payment_Plan__c = pp.Id, Name = 'Payment 3', Amount__c = 120, Due_Date__c = Date.today().addDays(30), Next_Payment_Due_Date__c = null));
		
		insert pplis;
		
		//pplis[0].Amount_Paid__c = pplis[0].Amount__c * 0.1;
		//pplis[0].Payment_Date__c = Date.today();
		//pplis[0].Next_Payment_Due_Date__c = Date.today().addDays(15);
		
		Test.startTest();
		Payment__c payment = new Payment__c();
		payment.Billing_Account__c = ba.id;
		payment.Payment_Source_Code__c = 6;
		payment.Payment_ID__c = '124124124';
		payment.Amount__c = pplis[0].Amount__c * 0.1;
		
		Payment__c payment1 = new Payment__c();
		payment1.Billing_Account__c = ba.id;
		payment1.Payment_Source_Code__c = 6;
		payment1.Payment_ID__c = '1241241242';
		payment1.Amount__c = pplis[1].Amount__c * 0.1;
		
		List<Payment__c> payments = new List<Payment__c>{payment, payment1};
		
		insert payments;
		//update pplis[0];
		
		//DataBase.executeBatch(new PaymentAllocationBatch());
		CollectionBatchStartContoller con = new CollectionBatchStartContoller();
		con.startJob();
		
		Test.stopTest();
		
	}

}