Production/Production/src/objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Step_Communication_Type__c</fullName>
        <label>Step Communication Type</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/Production/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Production/Production/src/objects/Collection_Path__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag indicates if the Path is active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Collection Path</label>
    <nameField>
        <label>Collection Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Production/Production/src/objects/Collection_Step__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Collection_Path__c</fullName>
        <label>Collection Path</label>
        <referenceTo>Collection_Path__c</referenceTo>
        <relationshipLabel>Collection Steps</relationshipLabel>
        <relationshipName>Collection_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Days_on_this_step__c</fullName>
        <label>Days on this step</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Proceed_if_faliure__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Proceed if faliure</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Step_Communication_Type__c</fullName>
        <label>Step Communication Type</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step_type__c</fullName>
        <label>Step type</label>
        <picklist>
            <picklistValues>
                <fullName>Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disconnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refer to Write off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wait</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Defaulted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>is_Default_Next_Step__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates that the step should be considered as default next step</description>
        <label>is Default Next Step</label>
        <type>Checkbox</type>
    </fields>
    <label>Collection Step</label>
    <nameField>
        <label>Collection Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Production/Production/src/objects/Collection_Step_Action__c.object
<CustomObject>
    <fields>
        <fullName>Collection_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collection Step</label>
        <referenceTo>Collection_Step__c</referenceTo>
        <relationshipLabel>Collection Step Actions</relationshipLabel>
        <relationshipName>Collection_Step_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>GoTo Step</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Collection Step Action</label>
    <nameField>
        <label>Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Step Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Production/Production/src/objects/Collection_Step_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Action</label>
        <referenceTo>Collection_Step_Action__c</referenceTo>
        <relationshipLabel>Collection Step Criterias</relationshipLabel>
        <relationshipName>Collection_Step_Criterias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Collection_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collection Step</label>
        <referenceTo>Collection_Step__c</referenceTo>
        <relationshipLabel>Collection Step Criterias</relationshipLabel>
        <relationshipName>Collection_Step_Criterias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exit_Criteria_Type__c</fullName>
        <label>Exit Criteria Type</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud Flag Set</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expression__c</fullName>
        <label>Expression</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Order_of_Execution__c</fullName>
        <label>Order of Execution</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Entry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Collection Step Criteria</label>
    <nameField>
        <label>Collection Step Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Step Criterias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Production/Production/src/classes/CollectionHelper.cls
public with sharing class CollectionHelper {

	static Map<Id, Collection_Path__c>  allPathsMap = new  Map<Id, Collection_Path__c>();	
	static Map<Id, Collection_Step_Criteria__c>  allCriteriaMap = new  Map<Id, Collection_Step_Criteria__c>();	
	
		
	public static Map<Id, Collection_Path__c> getAllPaths(){
		if ( allPathsMap.size() == 0 ){
			Map<Id, Collection_Path__c> allPaths = 
					new  Map<Id, Collection_Path__c>( [SELECT name, id, active__c, 
										( SELECT Name, Active__c, Days_on_this_step__c, Proceed_if_faliure__c, 
											Step_type__c, Cost__c, Sequence__c, Step_Communication_Type__c, is_Default_Next_Step__c 
									 		from Collection_steps__r order by Sequence__c) 
									 from Collection_Path__c]);
			allPathsMap = allPaths;	 				 
		}
		return allPathsMap; 
	} 


	public static Map<Id, Collection_Step_Criteria__c> getAllCriteriaMap(){
		if ( allCriteriaMap.size() == 0 ){
			Map<Id, Collection_Step_Criteria__c> allCriterias = 
					new  Map<Id, Collection_Step_Criteria__c>( [Select c.Type__c, c.Order_of_Execution__c, c.Name, c.Id, c.Expression__c, c.Collection_Step__c, c.Exit_Criteria_Type__c,
																c.Action__r.Collection_Step__c, c.Action__r.Value__c, c.Action__r.Type__c, c.Action__r.Name, c.Action__c 
													   From Collection_Step_Criteria__c c ] );
			allCriteriaMap = allCriterias;	 				 
		}
		return allCriteriaMap; 
	} 
	



	public static Collection_Path__c getPathById ( Id pathId ) {
		return getAllPaths().get ( pathId );
	}

/*
	public static Collection_Step__c getFirstStepForPath ( Id pathId ) {
		Collection_Path__c path = getAllPaths().get( pathId );
		
		if (path != null && path.Collection_steps__r != null && path.Collection_steps__r.size() > 0){
			// return the first default step from the Collection_steps__r
				return path.Collection_steps__r[0];	 
		}
		return null;
	}
	*/
	
	public static Collection_Step__c getFirstStepForPath ( Id pathId ) {
		return getDeafultNextStep ( pathId, null );
	}
	
	

	public static Collection_Step__c getStepForPath ( Id pathId, Id stepId ) {
		Collection_Path__c path = getAllPaths().get( pathId );
		
		if (path != null && path.Collection_steps__r != null && path.Collection_steps__r.size() > 0){
			// return the first step from the Collection_steps__r
			
			for (Collection_Step__c step : path.Collection_steps__r){
				if (step != null && step.id == stepId ){
					return step;
				}
			}
		}
		
		return null;
	}
	
	public static Collection_Step__c getDeafultNextStep ( Id pathId, Id stepId ) {
		Collection_Path__c path = getAllPaths().get( pathId );
		boolean foundStep = false;
		// move to first step
		if ( stepId == null ){
			foundStep = true;
		}
		
		if (path != null && path.Collection_steps__r != null && path.Collection_steps__r.size() > 0){
			// return the first step from the Collection_steps__r
			
			for (Collection_Step__c step : path.Collection_steps__r){
				if(foundStep){
					if ( step.is_Default_Next_Step__c ) {
						return step;
					}// if its not the default next step then will let it go on to the next one
				}
				
				if (step != null && step.id == stepId ){
					foundStep = true;
				}
			}
		}
		
		return null;
	}	
	
	public static Collection_Step__c getStepByName ( Id pathId, String stepName ) {
		Collection_Path__c path = getAllPaths().get( pathId );
		if (path != null && path.Collection_steps__r != null && path.Collection_steps__r.size() > 0){
			for (Collection_Step__c step : path.Collection_steps__r){
				if (step != null && step.Name == stepName ){
					return step;
				}
			}
		}
		
		return null;
	}	
		
	
	 /* When the Status of a PP or P2P is set to Open, a Case needs to be created.
	    This will be either at the creation of the record if it doesn't need to be submitted for Approval, or when it is Approved
	 */
	 /*
	 public static void createCollectionCaseForBillingAccounts(List<Billing_Account__c> billingAccountsForPPs, Map<Id, Id> billingAccountToPaymentPathMap) {
	 	
	 	List<CollectionAccountInfo> infos = new List<CollectionAccountInfo>();
	 	
	 	Set<Id> billingAccountIds = billingAccountToPaymentPathMap.keyset(); 
	 	
	 	List<Billing_Account__c> billingAccountsForPPs = database.query('select ' + 
                                                            SObjectHelper.getFieldListForSOQL('Billing_Account__c') + 
                                                        ' from Billing_Account__c where id IN :billingAccountIds');
                                                        
        for (Billing_Account__c ba : billingAccountsForPPs) {
        	infos.add(new CollectionAccountInfo(ba, billingAccountToPaymentPathMap.get(ba.Id)));
        	system.debug('******** Creating CollectionAccountInfo for ' + ba.Id);
        }
        
        PathHandler.assignPathsInBulk(infos);
	 }
	 */

	public static Id getFirstStepIdForPath ( Id pathId ) {
		Collection_Step__c step = getFirstStepForPath( pathId );
		if(step != null){
			return step.id;
		}
		return null;
	}


	public static Id getDeafultNextStepId ( Id pathId, Id stepId ) {
		Collection_Step__c step = getDeafultNextStep(pathId, stepId);
		if(step != null){
			return step.Id;
		}
		return null;
	}


	public static Collection_Step_Criteria__c getStepExitCriteriaByAction ( Id stepId, string action, string additionalCriteria ){	
		system.debug( 'stepId>>>>>>>>'+stepId);
		system.debug( 'action>>>>>>>>'+action);
		system.debug( 'additionalCriteria>>>>>>>>'+additionalCriteria);
		if ( additionalCriteria ==  null ) additionalCriteria = '';	
		
		for ( Collection_Step_Criteria__c criteria : getAllCriteriaMap().values() ){
			system.debug( '------criteria.Collection_Step__c-'+criteria.Collection_Step__c+'--stepId--' + stepId );
			system.debug( '------criteria.Exit_Criteria_Type__c-' + criteria.Exit_Criteria_Type__c + '-----action-----' + action );
			system.debug( '------criteria.Expression__c-----' + criteria.Expression__c + '-----additionalCriteria-----' + additionalCriteria );
			if( criteria.Collection_Step__c == stepId && criteria.Exit_Criteria_Type__c == action && Common.getBlankIfNull( criteria.Expression__c ) ==  Common.getBlankIfNull( additionalCriteria ) ){
				return criteria;
			}
		}
		return null;
	}

}