Production/Production/src/objects/Callback_Form__c.object
<CustomObject>
    <description>Initially used for Social Media cases, this online form feeds into Salesforce to allow agents to schedule callbacks against cases.</description>
    <fields>
        <fullName>Case_Number__c</fullName>
        <description>Case Number received from Online form.</description>
        <label>Case Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Callback Forms</relationshipLabel>
        <relationshipName>Callback_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Callback Form</label>
    <nameField>
        <displayFormat>CB-{0000000}</displayFormat>
        <label>Callback Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callback Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Production/Production/src/classes/TestCallBackForm.cls
/**
* Test class created for testing the functionality of CallBack Form
* being called and inserted using SOAP calls from TT online portal.
*
*/
@isTest
public with sharing class TestCallBackForm {
	/**
	* Public test method used for testing inserting of
	* a callback form into database.
	*/
	public static testMethod void testCallbackForm() {
		Case c = new Case();
		c.Status = Constants.CaseStatus_New;
		insert c;

		c = [SELECT CaseNumber, Id, Status FROM Case WHERE Id = :c.Id];

		CallBack_Form__c form = new CallBack_Form__c();
		form.Case__c = c.Id;
		form.Case_Number__c = c.CaseNumber;
		insert form;

		CallBack_Form__c formAfterInsert = [SELECT Case_Number__c, Case__c FROM CallBack_Form__c WHERE Id = :form.Id];
		//Check that form was inserted correctly into the database
		System.assertNotEquals(formAfterInsert, null);
		System.assertEquals(formAfterInsert.Case_Number__c, c.CaseNumber);

		Case caseAfterCallback = [SELECT Status FROM Case WHERE Id = :formAfterInsert.Case__c];
		//Check if the case status changed from 'New' to 'Customer Responded'
		System.assertEquals(caseAfterCallback.Status, Constants.CaseStatus_CustomerResponded);
	}
}