Production/Production/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>R6Service__SocialPersona__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the SocialPerson that made the post that generated the case.</description>
        <inlineHelpText>The Social Persona that generated the case.</inlineHelpText>
        <label>Social Persona</label>
        <referenceTo>SocialPersona</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Production/Production/src/objects/Social_Media_Verification_Form__c.object
<CustomObject>
    <description>Social Media Verification Form used to link Social Personas &amp; Community Users to Contacts and Accounts.</description>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>Account Number from Web form used to link to Salesforce case.</description>
        <label>Account Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SF_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to link the Social Media Verification object to a related case.</description>
        <label>SF Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Social Media Verification Forms</relationshipLabel>
        <relationshipName>Social_Media_Verification_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Social Media Verification Form</label>
    <nameField>
        <displayFormat>SMVF-{00000000}</displayFormat>
        <label>SM Verification Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Social Media Verification Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Production/Production/src/classes/SocialMediaVerificationFormHandler.cls
public class SocialMediaVerificationFormHandler {

	/**
     *  After insert trigger handler.
     */
    public static void handleAfterInsert(map<id, Social_Media_Verification_Form__c> newForms) {
    	
    	Set<Id> keys = newForms.keySet();
    	List<Social_Media_Verification_Form__c> newFormsExtended = database.query('select SF_Case__r.ContactId, SF_Case__r.R6Service__SocialPersona__r.ParentId, ' + 
    																					SObjectHelper.getFieldListForSOQL('Social_Media_Verification_Form__c') + 
    													' from Social_Media_Verification_Form__c where id IN :keys');  
    													
    	linkSocialPersonasAndCasesToExistingContact(newFormsExtended);
    }
    
    /*
     * Based on the SMVF's Account No, link Case and Social Persona to existing Contact (if exists)
     */
    public static void linkSocialPersonasAndCasesToExistingContact(List<Social_Media_Verification_Form__c> newFormsExtended) {
    	
    	// Get existing SF Contact based on Acc No. if exists, link Case and Social Persona to it.
    	List<SObject> objectsToLink = new List<SObject>();
    	
    	Set<String> spAccountNos = new Set<String>();
    	
    	for (Social_Media_Verification_Form__c f : newFormsExtended) {
    		if (f.Account_Number__c != null) {
    			spAccountNos.add(String.valueof(f.Account_Number__c));
    		}
    	}
    	
    	List<Contact> existingContacts = [select Id, Email, Account.AccountNumber from Contact where Account.AccountNumber in :spAccountNos];
    	
    	//Construct a map of potentially relevant Contacts by Account No
    	Map<String, List<Contact>> contactsByAccountNoMap = new Map<String, List<Contact>>();
    	for (Contact c : existingContacts) {
    		if (!contactsByAccountNoMap.containsKey(c.Account.AccountNumber)) {
    			contactsByAccountNoMap.put(c.Account.AccountNumber, new List<Contact> {c});
    		}
    		else {
    			//Currently Account-Contact is 1-1, but just to handle 1 to many in the future..
    			contactsByAccountNoMap.get(c.Account.AccountNumber).add(c);
    		}
    	} 
    	
    	//Get existing Contact if exists    	
    	for (Social_Media_Verification_Form__c f : newFormsExtended) {
    		if (f.Account_Number__c != null && contactsByAccountNoMap.containsKey(String.valueof(f.Account_Number__c)) && 
    				contactsByAccountNoMap.get(String.valueof(f.Account_Number__c)) != null && contactsByAccountNoMap.get(String.valueof(f.Account_Number__c)).size() > 0) {
    					
				Contact contactFound = contactsByAccountNoMap.get(String.valueof(f.Account_Number__c)).get(0);
				f.SF_Case__r.ContactId = contactFound.Id;
				f.SF_Case__r.R6Service__SocialPersona__r.ParentId = contactFound.Id;
				
				objectsToLink.add(f.SF_Case__r);
				objectsToLink.add(f.SF_Case__r.R6Service__SocialPersona__r);	
    		}
    	}
    	
    	if (objectsToLink.size() > 0) {
    		update objectsToLink;
    	}
    }
    
    
}