Production/Production/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ChatKey__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>ChatKey</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

Production/Production/src/objects/LiveChatTranscript.object
<CustomObject>
    <fields>
        <fullName>Chat_Key__c</fullName>
        <description>Used for matching the Post Chat Survey object (Chat Request Time + _ + Chat Start Time)</description>
        <externalId>true</externalId>
        <label>Chat Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

Production/Production/src/objects/Post_Chat_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Chat_Key__c</fullName>
        <description>Use for Matching to the Live Chat Transcript (Chat Request Time + _ + Chat Start Time)</description>
        <externalId>true</externalId>
        <label>Chat Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Chat_Transcript__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Live Chat Transcript</label>
        <referenceTo>LiveChatTranscript</referenceTo>
        <relationshipLabel>Post Chat Surveys</relationshipLabel>
        <relationshipName>Post_Chat_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Post Chat Survey</label>
    <nameField>
        <displayFormat>PCS-{0000}</displayFormat>
        <label>Post Chat Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Chat Surveys</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/Production/src/classes/TestPostChatSurveyTriggers.cls
@isTest
private class TestPostChatSurveyTriggers {
	
	static testMethod void testLinkedWithTranscriptsAfterInsert() {
	 
		/* after Survey Records have been inserted, if not associated with Transcripts, find matching Transcripts */
		
		/*
		DateTime reqTime = DateTime.now();
		DateTime strTime = DateTime.now().addMinutes(10);
		
		String expectedChatKey = Datetime.newInstance(reqTime.Year(),reqTime.Month(),reqTime.Day(),reqTime.Hour(),reqTime.Minute(),0) +  '_' + 
								Datetime.newInstance(strTime.Year(),strTime.Month(),strTime.Day(),strTime.Hour(),strTime.Minute(),0);
								
		// Create Case for chat key - Required
		Case laCase = new Case(ChatKey__c = '12345');
		insert laCase;
		
		// Insert Live Chat Transcript for this chatKey
		LiveChatVisitor visitor = new LiveChatVisitor();
		insert visitor;
		
		LiveChatTranscript lct = new LiveChatTranscript(RequestTime = reqTime, StartTime = strTime, Chat_Key__c = expectedChatKey, chatKey = '12345',
														LiveChatVisitorId = visitor.Id);
		insert lct;
								
		//Create a Post Chat Survey
		Post_Chat_Survey__c survey = new Post_Chat_Survey__c(Chat_Key__c = expectedChatKey);
		insert survey;
		
		//Retrieve and assert
		Post_Chat_Survey__c savedSurvey = [select Live_Chat_Transcript__c from Post_Chat_Survey__c where Id = :survey.Id];
		system.assertEquals(lct.Id, savedSurvey.Live_Chat_Transcript__c);
		*/
		
	}

}