Production/Production/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>R6Service__SocialPersona__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the SocialPerson that made the post that generated the case.</description>
        <inlineHelpText>The Social Persona that generated the case.</inlineHelpText>
        <label>Social Persona</label>
        <referenceTo>SocialPersona</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Production/Production/src/objects/Social_Media_Verification_Form__c.object
<CustomObject>
    <description>Social Media Verification Form used to link Social Personas &amp; Community Users to Contacts and Accounts.</description>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>Account Number from Web form used to link to Salesforce case.</description>
        <label>Account Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Case_Number__c</fullName>
        <description>Case Number from Web form used to link to Salesforce case.</description>
        <label>Case Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SF_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to link the Social Media Verification object to a related case.</description>
        <label>SF Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Social Media Verification Forms</relationshipLabel>
        <relationshipName>Social_Media_Verification_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Social Media Verification Form</label>
    <nameField>
        <displayFormat>SMVF-{00000000}</displayFormat>
        <label>SM Verification Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Social Media Verification Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Production/Production/src/classes/TestSocialMediaVerificationFormTriggers.cls
@isTest
private class TestSocialMediaVerificationFormTriggers {
	
	static testMethod void testLinkPersonaAndCaseToContact_ContactExists() {
		
		Decimal accNo = 12345;
		Account acc = new Account (Name = 'Test_Acc_1', AccountNumber = String.valueOf(accNo));
		insert acc;
		
		Contact con = new Contact (AccountId = acc.Id, LastName = 'Testius');
		insert con;
		
		//Create new Social Persona
		SocialPersona per = new SocialPersona(Name = 'Test Persona 1', ParentId = con.Id, Provider = 'Facebook');
		insert per;
		
		//Create a Case
		RecordType socialMediaRecordType = [select Id from RecordType where SObjectType = 'Case' and Name = :Constants.CaseRecordType_SocialMedia];
		Case c = new Case (RecordTypeId = socialMediaRecordType.Id, Status = Constants.CaseStatus_CustomerResponded, R6Service__SocialPersona__c = per.Id);
		insert c;
		
		Test.startTest();
		
		//Create a SMVF
		Social_Media_Verification_Form__c form = new Social_Media_Verification_Form__c(SF_Case__c = c.Id, Account_Number__c = accNo, Case_Number__c = 12);
		insert form;
		
		Test.stopTest();
		
		//Retrieve and assert
		Social_Media_Verification_Form__c savedForm = database.query('select SF_Case__r.ContactId, SF_Case__r.R6Service__SocialPersona__r.ParentId, ' + 
    																					SObjectHelper.getFieldListForSOQL('Social_Media_Verification_Form__c') + 
    													' from Social_Media_Verification_Form__c where id = \'' + form.Id + '\'');  
    													
    	system.assertEquals(con.Id, savedForm.SF_Case__r.ContactId);
    	system.assertEquals(con.Id, savedForm.SF_Case__r.R6Service__SocialPersona__r.ParentId);
	}
	
	static testMethod void testLinkPersonaAndCaseToContact_ContactNotExists() {
		
	}

}