Production/Production/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Outcome__c</fullName>
        <description>Possible outcomes of raising this case</description>
        <inlineHelpText>What is the outcome of raising this case?</inlineHelpText>
        <label>Case Outcome</label>
        <picklist>
            <picklistValues>
                <fullName>Billing Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boost – Add boost – Provide details of boost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call pricing – International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor comparison – provide competitor detail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract - cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract – End date enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract – length of contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract – Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer looking for a better offer – provide details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer wants to cancel account – provide details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email address query</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fibre enquiry – package, price information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home mover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation – Powerline Adaptors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation query – Price, process, timescales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other – please insert question asked?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Package details – what is included in the package ?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Router questions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speed requirements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV – Aerial/Availability/Multi room question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV – Self install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV – Upgrade to TV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV – YouView box details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable to get TV or Broadband – Select reason below</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VLR – Adding VLR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VLR – Payment issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VLR – Pricing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Close_Reason__c</fullName>
        <inlineHelpText>Reason for closing the case</inlineHelpText>
        <label>Close Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalation form completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer to call Contact Centre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Gone Away</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Responded to Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call-back Booked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Production/Production/src/classes/CaseFeedCloseController.cls
public class CaseFeedCloseController {

    public Case caseRec {get; set;}

    public CaseFeedCloseController(ApexPages.StandardController controller) {
        Case c = (Case)controller.getRecord();

        caseRec = [select Id, Subject, Case_Outcome__c, Close_Reason__c, Reason, Description, Status from Case where Id = :c.Id];

    }

    public PageReference closeCase() {
        caseRec.Status = Constants.CaseStatus_Closed;
        update caseRec;

        return null;
    }

}