Production/Production/src/objects/Community_Postback_Comment__c.object
<CustomObject>
    <description>Used for posting Agent comments on a Case as replies to the related Lithium thread</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Community Postback Comments</relationshipLabel>
        <relationshipName>Community_Postback_Comments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Postback_Comment__c</fullName>
        <description>Comments entered here are posted back to the Lithium community as replies to the thread</description>
        <label>Postback Comment</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Community Postback Comment</label>
    <nameField>
        <displayFormat>Comment-{0000}</displayFormat>
        <label>Postback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Postback Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Production/Production/src/objects/LithiumSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Lithium Settings for Lithium-SFDC integration</description>
    <fields>
        <fullName>Username__c</fullName>
        <description>Lithium username to be used while making call outs to the REST API</description>
        <inlineHelpText>Enter the Lithium username to be used in Lithium API callouts</inlineHelpText>
        <label>Lithium Login</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Lithium Settings</label>
</CustomObject>

Production/Production/src/classes/TestCommunityPostbackCommentTriggers.cls
@isTest
private class TestCommunityPostbackCommentTriggers {
	
	static Case c;
	
	static void prepareData(Integer socialPostsNumber) {
		Account acc = new Account (Name = 'Test_Acc_1');
		insert acc;
		
		Contact con = new Contact (AccountId = acc.Id, LastName = 'Testius');
		insert con;
		
		//Create a (Lithium) Case
		RecordType lithiumCaseRecordType = [select Id, Name from RecordType where SObjectType = 'Case' and Name = :Constants.CaseRecordType_Lithium LIMIT 1];
		c = new Case (ContactId = con.Id, Status = Constants.CaseStatus_CustomerResponded, RecordTypeId = lithiumCaseRecordType.Id);
		insert c;
		
		//Create Custom Setting required by Lithium
		LithiumSettings__c sett = new LithiumSettings__c(Name='DefaultSetting', Username__c = 'ctest');
		insert sett;
		
		List<Community_Postback_Comment__c> comments = new List<Community_Postback_Comment__c>();
		for (Integer i=0; i < socialPostsNumber; i++) {
			comments.add(new Community_Postback_Comment__c(Postback_Comment__c = 'A comment', Case__c = c.Id));
		}
		
		insert comments;
	}
	
	static testMethod void testLithiumCaseResolutionAfterInsert() {
		
		prepareData(1);
		
		//Re-fetch Case and assert
		Case refCase = [select Id, Status from Case where Id = :c.Id];
		system.assertEquals(Constants.CaseStatus_Resolved, refCase.Status);
	}
	
	static testMethod void testLithiumCaseResolutionAfterInsert_Bulk() {
		
		prepareData(200);
		
		//Re-fetch Case and assert
		Case refCase = [select Id, Status from Case where Id = :c.Id];
		system.assertEquals(Constants.CaseStatus_Resolved, refCase.Status);
	}

}