Production/Production/src/objects/Payment_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Installments__c</fullName>
        <label>Number of Installments</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Production/Production/src/objects/Payment_Plan_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Payment Plan Lines</relationshipLabel>
        <relationshipName>Payment_Plan_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Plan Line Item</label>
    <nameField>
        <label>Payment Plan Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plan Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Production/Production/src/classes/PaymentPlanSummaryController.cls
public with sharing class PaymentPlanSummaryController {

	public String paymentPlanId {
		get {return paymentPlanId;} 
		set {paymentPlanId = value; retrieveData();}
	}
	
	public decimal monthlyInstallmentAmount {get; set;}
		
	public decimal finalInstallment {get; set;}
	
	public Integer noOfInstallments {get; set;}
	
	public Payment_Plan__c pp {get; set;}

	public void retrieveData() {
		
		List<Payment_Plan__c>pps = database.query('select ' + 
                                        SObjectHelper.getFieldListForSOQL('Payment_Plan__c') + 
                                    ' , (select ' +  SObjectHelper.getFieldListForSOQL('Payment_Plan_Line_Item__c') +
                                    	' from Payment_Plan_Lines__r order by Due_Date__c asc) '
                                    + 'from Payment_Plan__c where Id = :paymentPlanId ');
                                    
        
       // ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'***** paymentPlanId: ' + paymentPlanId));
        if (pps != null && pps.size() > 0) {
        	pp = pps[0];
        	
        	noOfInstallments = pp.Number_of_Installments__c.intValue();
        	
        	if (pp.Payment_Plan_Lines__r != null && pp.Payment_Plan_Lines__r.size() > 0) {
	        	monthlyInstallmentAmount = pp.Payment_Plan_Lines__r[0].Amount__c;
	        	finalInstallment = pp.Payment_Plan_Lines__r[pp.Payment_Plan_Lines__r.size()-1].Amount__c;
	        }
        }
	}		
}